/* =========================================================================
   Pokémon Black 2 / White 2 — Streamlined Route (Part 10 → Legendaries)
   Story content condensed from Bulbapedia's B2W2 walkthrough (Parts 1–22).
   Maps from mewmaps.org. Personal reference only.

   Step types:
     story  – required to advance the main story
     boss   – required battle (Gym Leader, rival, Team Plasma, League)
     legend – a legendary Pokémon you can catch here
     key    – a key item or action needed for a legendary
     prep   – catch prep / shopping (strongly recommended)
     heal   – free healing spot
     tip    – minor helpful extra (hidden unless "Show extras" is on)
   Version-specific text uses {b2|w2} placeholders, swapped at render time.
   ========================================================================= */
(() => {
"use strict";


// Region-map pin coordinates (percent of map width/height)
const PINS = {
  "Route 19": [10.5, 77.5],
  "Floccesy Town": [15.5, 75.5],
  "Floccesy Ranch": [16.5, 66.5],
  "Virbank City": [28.0, 73.0],
  "Route 4": [50.6, 73.5],
  "Desert Resort": [44.6, 65.6],
  "Join Avenue": [51.0, 66.0],
  "Nimbasa City": [53.3, 62.4],
  "Route 5": [45.0, 61.4],
  "Driftveil Drawbridge": [35.8, 60.4],
  "Pokémon World Tournament": [26.7, 66.6],
  "Route 6": [17.5, 56.2],
  "Mistralton Cave": [22.9, 50.5],
  "Chargestone Cave": [18.8, 48.4],
  "Mistralton City": [13.0, 43.5],
  "Route 7": [20.5, 34.0],
  "Celestial Tower": [15.6, 33.5],
  "Twist Mountain": [26.3, 35.0],
  "Lentimas Town": [74.5, 50.0],
  "Strange House": [81.5, 49.8],
  "Reversal Mountain": [78.5, 49.3],
  "Undella Town": [91.5, 49.5],
  "Route 13": [78.0, 42.1],
  "Lacunosa Town": [78.8, 33.8],
  "Route 12": [73.8, 38.5],
  "Village Bridge": [64.2, 36.4],
  "Route 11": [55.8, 38.7],
  "Opelucid City": [50.0, 33.0],
  "Route 9": [45.0, 34.0],
  "Marine Tube": [98.0, 41.6],
  "Humilau City": [92.5, 33.3],
  "Route 22": [85.5, 28.5],
  "Route 21": [95.0, 38.7],
  "Seaside Cave": [86.3, 43.2],
  "Giant Chasm": [81.3, 29.5],
  "Route 23": [75.0, 26.0],
  "Victory Road": [70.0, 20.3],
  "Pokémon League": [66.3, 14.0],
  "N's Castle": [66.3, 17.5],
  "Aspertia City": [5.8, 83.5],
  "Route 20": [21.5, 74.0],
  "Cave of Being": [17.5, 79.0],
  "Driftveil City": [32.0, 61.0],
  "Clay Tunnel": [28.3, 58.3],
  "Icirrus City": [34.3, 36.0],
  "Route 8": [35.8, 33.8],
  "Tubeline Bridge": [41.0, 35.0],
  "Dragonspiral Tower": [31.8, 30.5],
  "Route 14": [87.5, 56.2],
  "Abundant Shrine": [67.9, 52.5],
  "Black City / White Forest": [79.2, 61.9],
  "Route 15": [73.3, 62.4],
  "Marvelous Bridge": [65.4, 58.8],
  "Castelia City": [52.0, 84.0],
  "Skyarrow Bridge": [65.8, 77.0],
  "Nacrene City": [76.5, 69.0],
  "Striaton City": [91.5, 67.5],
  "Dreamyard": [93.5, 69.0],
  "Route 1": [91.7, 82.0],
  "Route 17": [84.5, 85.0],
  "Route 18": [75.0, 85.0],
};

// Location maps from mewmaps.org, loaded straight from MewMaps' public Google Drive files (not rehosted).
// `locs`: other place names this map covers. A step at (or text mentioning) the map's name or one
// of its locs gets a button for this map, so you see the inside instead of only the region pin.
const MAPS = {
  "castelia-city": { name: "Castelia City", drive: "1hxuSbrhCsN3Vba-7xyQBLyOMmyFlmm8w", locs: ["Thumb Pier"] },
  "castelia-sewers": { name: "Castelia Sewers", drive: "1DSaauTP-sz-JBeAcMfLSi9lvWjmf0hyU" },
  "relic-castle": { name: "Relic Castle", drive: "1iUuxGsNFwRrZ8mR_woRq9um8ZgM8qrwn" },
  "relic-passage": { name: "Relic Passage", drive: "1Xt48G9lF6tFXOul8oOnJnocj1gNgH3Jq" },
  "mistralton-cave": { name: "Mistralton Cave", drive: "1k9E36vidbFiaR1usXSrZf463_t0Gpz6j" },
  "chargestone-cave": { name: "Chargestone Cave", drive: "1avVR2iUzDl0IHXbsZwTZGiXFNXmBbSjB" },
  "celestial-tower": { name: "Celestial Tower", drive: "1kRI8-7nPqdSD7SZS-ZnRdPWKmJ4S_hMR" },
  "reversal-mountain": { name: "Reversal Mountain", drive: "1HgamUJfjx8_QPj8z5zMnqaR0FA7GSOQJ" },
  "giant-chasm": { name: "Giant Chasm", drive: "1-c7QeRPPfoe6LsxbSicIOZFkraLgmNse", locs: ["Crater Forest"] },
  // MewMaps has no Seaside Cave map, so these floors come from Bulbapedia's image archive.
  "seaside-cave-1f": { name: "Seaside Cave 1F", bulba: "Seaside Cave 1F B2W2.png", locs: ["Seaside Cave"] },
  "seaside-cave-b1f": { name: "Seaside Cave B1F", bulba: "Seaside Cave B1F B2W2.png" },
  "victory-road": { name: "Victory Road", drive: "10AUvP93VpTMOO4QY1WA7L-5TcLbfnseO" },
  "cave-of-being": { name: "Cave of Being", drive: "1d0FrYfUiozUwdid_TaZSvAkBt5fQrHlG" },
  "clay-tunnel": { name: "Clay Tunnel", drive: "13usfK6nS1KNKWdTA1WQJleQ_f7iZ-9no" },
  "underground-ruins": { name: "Underground Ruins", drive: "1T9HCf6zIBnXhiFRF6OzeoR5HrF81hxEm" },
  "twist-mountain": { name: "Twist Mountain", drive: "1gHQ6oyq9AeZxpVtIEmWVt7h8YNuO8Z5W" },
  "dragonspiral-tower": { name: "Dragonspiral Tower", drive: "1u2oOsiIZG_DzTvghtXEuFqBZ050gHXhZ" },
  "dreamyard": { name: "Dreamyard", drive: "1VH6MSwb5S2wWVM8uTfrNehJh-S9ZYdW6" },
  "pinwheel-forest": { name: "Pinwheel Forest", drive: "1NELmjwaMm-fcvWr3InBe-hkkSdKb2cZ9" },
  "wellspring-cave": { name: "Wellspring Cave", drive: "1c8GQrtqh5CHzMF7pORL6Op3VFsPplIUu" },
  "abyssal-ruins": { name: "Abyssal Ruins", drive: "13m038XZE-gMbCETCLke4OIr3sgN_bSo1" },
  "route-17-18-p2-lab": { name: "Routes 17 & 18 / P2 Lab", drive: "16N3eJcx325_iT5ADrgLfM8JiXy0TVZtA", locs: ["Route 17", "Route 18", "P2 Lab"] },

  // Close-up maps from Bulbapedia's image archive (town/route/building maps), for places MewMaps doesn't cover.
  // `bulba` is the archive file name; {B2|W2} picks the version's image.
  "aspertia-city": { name: "Aspertia City", bulba: "Aspertia City Summer B2W2.png" },
  "route-19": { name: "Route 19", bulba: "Unova Route 19 Summer B2W2.png" },
  "floccesy-town": { name: "Floccesy Town", bulba: "Floccesy Town Spring B2W2.png" },
  "route-20": { name: "Route 20", bulba: "Unova Route 20 Summer B2W2.png" },
  "floccesy-ranch": { name: "Floccesy Ranch", bulba: "Floccesy Ranch Summer B2W2.png" },
  "virbank-city": { name: "Virbank City", bulba: "Virbank City Spring B2W2.png" },
  "virbank-complex": { name: "Virbank Complex", bulba: "Virbank Complex exterior Summer B2W2.png" },
  "pokestar-studios": { name: "Pokéstar Studios", bulba: "Pokéstar Studios Summer B2W2.png" },
  "route-4": { name: "Route 4", bulba: "Unova Route 4 {B2|W2}.png" },
  "desert-resort": { name: "Desert Resort", bulba: "Desert Resort B2W2.png" },
  "join-avenue": { name: "Join Avenue", bulba: "Join Avenue B2W2.png" },
  "nimbasa-city": { name: "Nimbasa City", bulba: "Nimbasa City Summer B2W2.png" },
  "route-5": { name: "Route 5", bulba: "Unova Route 5 Spring B2W2.png" },
  "driftveil-drawbridge": { name: "Driftveil Drawbridge", bulba: "Driftveil Drawbridge BW.png" },
  "driftveil-city": { name: "Driftveil City", bulba: "Driftveil City Summer B2W2.png" },
  "pwt": { name: "Pokémon World Tournament", bulba: "Pokémon World Tournament B2W2.png", locs: ["PWT"] },
  "route-6": { name: "Route 6", bulba: "Unova Route 6 Spring B2W2.png" },
  "mistralton-city": { name: "Mistralton City", bulba: "Mistralton City Summer {B2|W2}.png" },
  "route-7": { name: "Route 7", bulba: "Unova Route 7 Spring B2W2.png" },
  "lentimas-town": { name: "Lentimas Town", bulba: "Lentimas Town B2W2.png" },
  "undella-town": { name: "Undella Town", bulba: "Undella Town Summer B2W2.png" },
  "route-13": { name: "Route 13", bulba: "Unova Route 13 Summer B2W2.png" },
  "lacunosa-town": { name: "Lacunosa Town", bulba: "Lacunosa Town Summer B2W2.png" },
  "route-12": { name: "Route 12", bulba: "Unova Route 12 Summer B2W2.png" },
  "village-bridge": { name: "Village Bridge", bulba: "Village Bridge Summer B2W2.png" },
  "route-11": { name: "Route 11", bulba: "Unova Route 11 Summer B2W2.png" },
  "opelucid-city": { name: "Opelucid City", bulba: "Opelucid City Summer {B2|W2}.png" },
  "route-9": { name: "Route 9", bulba: "Unova Route 9 Summer B2W2.png" },
  "tubeline-bridge": { name: "Tubeline Bridge", bulba: "Tubeline Bridge Top Down BWB2W2.png" },
  "marine-tube": { name: "Marine Tube", bulba: "Marine Tube B2W2.png" },
  "humilau-city": { name: "Humilau City", bulba: "Humilau City Spring B2W2.png" },
  "route-21": { name: "Route 21", bulba: "Unova Route 21 Summer B2W2.png" },
  "route-22": { name: "Route 22", bulba: "Unova Route 22 Summer B2W2.png" },
  "route-23": { name: "Route 23", bulba: "Unova Route 23 Summer B2W2.png" },
  "route-14": { name: "Route 14", bulba: "Unova Route 14 Summer B2W2.png" },
  "marvelous-bridge": { name: "Marvelous Bridge", bulba: "Marvelous Bridge BW.png" },
  "skyarrow-bridge": { name: "Skyarrow Bridge", bulba: "Skyarrow Bridge BW.png" },
  "nacrene-city": { name: "Nacrene City", bulba: "Nacrene City Summer B2W2.png" },
  "striaton-city": { name: "Striaton City", bulba: "Striaton City Summer B2W2.png" },
  "virbank-gym": { name: "Virbank Gym", bulba: "Virbank Gym B2W2.png" },
  "castelia-gym": { name: "Castelia Gym", bulba: "Castelia Gym B2W2.png" },
  "nimbasa-gym": { name: "Nimbasa Gym", bulba: "Nimbasa Gym B2W2.png" },
  "driftveil-gym": { name: "Driftveil Gym", bulba: "Driftveil Gym B2W2.png" },
  "mistralton-gym": { name: "Mistralton Gym", bulba: "Mistralton Gym B2W2.png" },
  "humilau-gym": { name: "Humilau Gym", bulba: "Humilau Gym B2W2.png" },
  "plasma-frigate": { name: "Plasma Frigate B1F", bulba: "Plasma Frigate B1F B2W2.png", locs: ["Plasma Frigate"] },
};

/* ---------------------------------------------------------------------------
   Legendaries obtainable in-game (no events, no Dream Radar).
   ver: "both" | "b2" | "w2"
--------------------------------------------------------------------------- */
const LEGENDS = [
  { id: "cobalion",  name: "Cobalion",  dex: 638, lvl: 45, types: ["Steel", "Fighting"], ver: "both", phase: "story",
    where: "Route 13", step: "p12-cobalion",
    hit: "Fire, Fighting, Ground", avoid: "Dark moves (Justified boosts its Attack)",
    note: "If you KO it, it comes back at Lv65 after the Hall of Fame." },
  { id: "virizion",  name: "Virizion",  dex: 640, lvl: 45, types: ["Grass", "Fighting"], ver: "both", phase: "story",
    where: "Route 11", step: "p12-virizion",
    hit: "Flying (4×), Fire, Ice, Psychic", avoid: "Dark moves (Justified)",
    note: "If you KO it, it comes back at Lv65 after the Hall of Fame." },
  { id: "terrakion", name: "Terrakion", dex: 639, lvl: 45, types: ["Rock", "Fighting"], ver: "both", phase: "story",
    where: "Route 22", step: "p13-terrakion",
    hit: "Grass, Water, Ground, Fighting, Psychic, Steel", avoid: "Dark moves (Justified)",
    note: "If you KO it, it comes back after the Hall of Fame." },
  { id: "mesprit",   name: "Mesprit",   dex: 481, lvl: 65, types: ["Psychic"], ver: "both", phase: "post",
    where: "Celestial Tower roof", step: "pg-mesprit", requires: "Visit Cave of Being first",
    hit: "Bug, Ghost, Dark", avoid: "" },
  { id: "regirock",  name: "Regirock",  dex: 377, lvl: 65, types: ["Rock"], ver: "both", phase: "post",
    where: "Underground Ruins (via Clay Tunnel)", step: "pg-regirock",
    hit: "Water, Grass, Fighting, Ground, Steel", avoid: "" },
  { id: "registeel", name: "Registeel", dex: 379, lvl: 65, types: ["Steel"], ver: "both", native: "b2", phase: "post",
    where: "Underground Ruins — Iron Chamber", step: "pg-registeel", requires: "{Catch Regirock → Iron Key|Iron Key from a Black 2 game}",
    hit: "Fire, Fighting, Ground", avoid: "",
    other: "White 2 can't unlock this by itself. Get the Iron Key from a Black 2 game over Unova Link, or trade for Registeel." },
  { id: "regice",    name: "Regice",    dex: 378, lvl: 65, types: ["Ice"], ver: "both", native: "w2", phase: "post",
    where: "Underground Ruins — Iceberg Chamber", step: "pg-regice", requires: "{Iceberg Key from a White 2 game|Catch Regirock → Iceberg Key}",
    hit: "Fire, Fighting, Rock, Steel", avoid: "",
    other: "Black 2 can't unlock this by itself. Get the Iceberg Key from a White 2 game over Unova Link, or trade for Regice." },
  { id: "regigigas", name: "Regigigas", dex: 486, lvl: 68, types: ["Normal"], ver: "both", phase: "post",
    where: "Twist Mountain (hidden north chamber)", step: "pg-regigigas", requires: "Regirock + Regice + Registeel in party",
    hit: "Fighting", avoid: "",
    note: "Slow Start halves its Attack/Speed for 5 turns — best window to catch." },
  { id: "azelf",     name: "Azelf",     dex: 482, lvl: 65, types: ["Psychic"], ver: "both", phase: "post",
    where: "Route 23 (west forest)", step: "pg-azelf", requires: "Visit Cave of Being first",
    hit: "Bug, Ghost, Dark", avoid: "" },
  { id: "zekrom",    name: "Zekrom",    dex: 644, lvl: 70, types: ["Dragon", "Electric"], ver: "b2", phase: "post",
    where: "Dragonspiral Tower 7F", step: "pg-dragon", requires: "Beat N at N's Castle → Dark Stone",
    hit: "Ground, Ice, Dragon", avoid: "" },
  { id: "reshiram",  name: "Reshiram",  dex: 643, lvl: 70, types: ["Dragon", "Fire"], ver: "w2", phase: "post",
    where: "Dragonspiral Tower 7F", step: "pg-dragon", requires: "Beat N at N's Castle → Light Stone",
    hit: "Ground, Rock, Dragon", avoid: "" },
  { id: "kyurem",    name: "Kyurem",    dex: 646, lvl: 70, types: ["Dragon", "Ice"], ver: "both", phase: "post",
    where: "Giant Chasm (inner cave)", step: "pg-kyurem", requires: "Catch {Zekrom|Reshiram} first",
    hit: "Fighting, Rock, Steel, Dragon", avoid: "",
    note: "Hardest catch in the game — the best Master Ball target. Drops the DNA Splicers." },
  { id: "cresselia", name: "Cresselia", dex: 488, lvl: 68, types: ["Psychic"], ver: "both", phase: "post",
    where: "Marvelous Bridge", step: "pg-cresselia", requires: "Lunar Wing (Strange House)",
    hit: "Bug, Ghost, Dark", avoid: "" },
  { id: "uxie",      name: "Uxie",      dex: 480, lvl: 65, types: ["Psychic"], ver: "both", phase: "post",
    where: "Nacrene City (outside the Museum)", step: "pg-uxie", requires: "Visit Cave of Being first",
    hit: "Bug, Ghost, Dark", avoid: "" },
  { id: "latios",    name: "Latios",    dex: 381, lvl: 68, types: ["Dragon", "Psychic"], ver: "b2", phase: "post",
    where: "Dreamyard (east of Striaton)", step: "pg-lati",
    hit: "Dragon, Ice, Bug, Ghost, Dark", avoid: "Strong Dark moves (it's frail to them — don't KO it)" },
  { id: "latias",    name: "Latias",    dex: 380, lvl: 68, types: ["Dragon", "Psychic"], ver: "w2", phase: "post",
    where: "Dreamyard (east of Striaton)", step: "pg-lati",
    hit: "Dragon, Ice, Bug, Ghost, Dark", avoid: "Strong Dark moves (it's frail to them — don't KO it)" },
  { id: "heatran",   name: "Heatran",   dex: 485, lvl: 68, types: ["Fire", "Steel"], ver: "both", phase: "post",
    where: "Reversal Mountain B1F", step: "pg-heatran", requires: "Magma Stone (Route 18)",
    hit: "Ground (4×), Water, Fighting", avoid: "" },
];

// Bulbapedia walkthrough sections per part: [label, anchor] (powers the "More on Bulbapedia" lists)
const SECTIONS = {
  1: [["Intro", "Intro"], ["Aspertia City", "Aspertia_City"], ["Home", "Home"], ["Aspertia Outlook", "Aspertia_Outlook"], ["Pokémon Center", "Pokémon_Center"], ["Route 19", "Route_19"], ["Floccesy Town", "Floccesy_Town"]],
  2: [["Route 20", "Route_20"], ["Floccesy Ranch", "Floccesy_Ranch"], ["Floccesy Town", "Floccesy_Town"], ["Alder's house", "Alder's_house"], ["Pledge Grove", "Pledge_Grove"], ["Aspertia City", "Aspertia_City"], ["Trainers' School", "Trainers'_School"], ["Floccesy Town", "Floccesy_Town_2"], ["Route 20", "Route_20_2"]],
  3: [["Virbank City", "Virbank_City"], ["Virbank Complex", "Virbank_Complex"], ["Virbank Gym", "Virbank_Gym"], ["Pokéstar Studios", "Pokéstar_Studios"], ["Shooting a Movie", "Shooting_a_Movie"], ["Virbank City", "Virbank_City_2"], ["Team Plasma Appears", "Team_Plasma_Appears"], ["Route 20", "Route_20"], ["Virbank City", "Virbank_City_3"]],
  4: [["Castelia City", "Castelia_City"], ["Oceanfront Road", "Oceanfront_Road"], ["Castelia Street", "Castelia_Street"], ["Mode Street", "Mode_Street"], ["Narrow Street", "Narrow_Street"], ["Gym Street", "Gym_Street"], ["Castelia Sewers", "Castelia_Sewers"], ["Castelia Gym", "Castelia_Gym"], ["Central Plaza", "Central_Plaza"], ["Street to Route 4", "Street_to_Route_4"]],
  5: [["Route 4 (Black 2)", "Route_4B2"], ["Battle the Pokémon Breeder", "Battle_the_Pokémon_Breeder"], ["Challenge Colress", "Challenge_Colress"], ["The Speed-Focused Girl", "The_Speed-Focused_Girl"], ["Time for a Trade", "Time_for_a_Trade"], ["The Maid of Mimicry", "The_Maid_of_Mimicry"], ["Rest House", "Rest_House"], ["Planned Expansion Area", "Planned_Expansion_Area"], ["Route 4 (White 2)", "Route_4W2"], ["Battle the Pokémon Breeder", "Battle_the_Pokémon_Breeder_2"], ["Challenge Colress", "Challenge_Colress_2"], ["The Maid of Mimicry", "The_Maid_of_Mimicry_2"], ["The Attack-Focused Guy", "The_Attack-Focused_Guy"], ["Time for a Trade", "Time_for_a_Trade_2"], ["Rest House", "Rest_House_2"], ["Desert Resort", "Desert_Resort"], ["The Nurse Heals Your Pokémon", "The_Nurse_Heals_Your_Pokémon"], ["Add a Funfest Mission", "Add_a_Funfest_Mission"], ["Relic Castle", "Relic_Castle"], ["Join Avenue", "Join_Avenue"], ["Become a Manager", "Become_a_Manager"], ["Development", "Development"]],
  6: [["Nimbasa City", "Nimbasa_City"], ["Pair up against the Subway Bosses", "Pair_up_against_the_Subway_Bosses"], ["Gear Station", "Gear_Station"], ["Big Stadium and Small Court", "Big_Stadium_and_Small_Court"], ["Musical Theater", "Musical_Theater"], ["Amusement Park", "Amusement_Park"], ["Hugh and Team Plasma face off", "Hugh_and_Team_Plasma_face_off"], ["Anville Town", "Anville_Town"], ["The Missing Pansage", "The_Missing_Pansage"], ["Funfest Mission", "Funfest_Mission"], ["Lost & Found", "Lost_&_Found"], ["The turntable", "The_turntable"], ["Route 16", "Route_16"], ["Bridge Gate", "Bridge_Gate"], ["Lostlorn Forest", "Lostlorn_Forest"]],
  7: [["Route 5", "Route_5"], ["Bianca's HM", "Bianca's_HM"], ["Hidden Grottoes Revealed", "Hidden_Grottoes_Revealed"], ["The Berry Seller", "The_Berry_Seller"], ["The Hungry Maid", "The_Hungry_Maid"], ["Battle the Musician", "Battle_the_Musician"], ["Roadblock", "Roadblock"], ["Driftveil Drawbridge", "Driftveil_Drawbridge"], ["Funfest Mission", "Funfest_Mission"], ["The Youngster's Wish", "The_Youngster's_Wish"], ["Driftveil City", "Driftveil_City"], ["Team Plasma, Old & New", "Team_Plasma,_Old_&_New"], ["Grand Hotel", "Grand_Hotel"], ["Luxury Suites", "Luxury_Suites"], ["Continental Hotel", "Continental_Hotel"], ["Chateau Hotel", "Chateau_Hotel"], ["Move Tutor", "Move_Tutor"], ["Driftveil Market", "Driftveil_Market"], ["Former Plasma Base", "Former_Plasma_Base"], ["Driftveil Gym", "Driftveil_Gym"]],
  8: [["Pokémon World Tournament", "Pokémon_World_Tournament"], ["Hidden Power Guy", "Hidden_Power_Guy"], ["Move Reminder", "Move_Reminder"], ["Move Deleter", "Move_Deleter"], ["Ultimate Move Tutor", "Ultimate_Move_Tutor"], ["Battle-Combo Move Tutor", "Battle-Combo_Move_Tutor"], ["World Tournament building", "World_Tournament_building"], ["Plasma Frigate", "Plasma_Frigate"], ["Relic Passage", "Relic_Passage"], ["North chamber", "North_chamber"], ["Middle chamber", "Middle_chamber"], ["Relic Castle", "Relic_Castle"], ["Relic Passage (cont.)", "Relic_Passage_2"], ["Middle chamber (cont.)", "Middle_chamber_2"], ["South chamber", "South_chamber"]],
  9: [["Route 6", "Route_6"], ["Meet up with Cheren", "Meet_up_with_Cheren"], ["Season Research Lab", "Season_Research_Lab"], ["A Legendary Pokémon Appears", "A_Legendary_Pokémon_Appears"], ["Mistralton Cave", "Mistralton_Cave"], ["Chargestone Cave", "Chargestone_Cave"], ["1F", "1F_2"], ["B1F", "B1F"], ["B2F", "B2F"], ["B1F (return)", "B1F_2"], ["1F (exit)", "1F_3"]],
  10: [["Mistralton City", "Mistralton_City"], ["The TM Collector", "The_TM_Collector"], ["Meet Professor Juniper and Skyla", "Meet_Professor_Juniper_and_Skyla"], ["Mistralton Cargo Service", "Mistralton_Cargo_Service"], ["The Runway", "The_Runway"], ["Route 7", "Route_7"], ["Trade with a Hiker", "Trade_with_a_Hiker"], ["Celestial Tower", "Celestial_Tower"], ["The Eastern House", "The_Eastern_House"], ["Mom Checks In", "Mom_Checks_In"], ["Twist Mountain", "Twist_Mountain"], ["Mistralton City (return)", "Mistralton_City_2"], ["Mistralton Gym", "Mistralton_Gym"], ["Juniper returns from Celestial Tower", "Juniper_returns_from_Celestial_Tower"], ["The Kids' Treasure", "The_Kids'_Treasure"], ["Mistralton Cargo Service (departure)", "Mistralton_Cargo_Service_2"]],
  11: [["Lentimas Town", "Lentimas_Town"], ["Juniper Tells a Story", "Juniper_Tells_a_Story"], ["Move Tutor", "Move_Tutor"], ["Strange House", "Strange_House"], ["Entrance Hall", "Entrance_Hall"], ["B1F", "B1F"], ["Entrance Hall (2)", "Entrance_Hall_2"], ["B1F (2)", "B1F_2"], ["Entrance Hall (3)", "Entrance_Hall_3"], ["Reversal Mountain (Black 2)", "Reversal_MountainB2"], ["Lentimas chamber", "Lentimas_chamber"], ["Main chamber", "Main_chamber"], ["Mountainside", "Mountainside"], ["Main chamber (2)", "Main_chamber_2"], ["Basement chamber", "Basement_chamber"], ["Main chamber (3)", "Main_chamber_3"], ["Undella chamber", "Undella_chamber"], ["Reversal Mountain (White 2)", "Reversal_MountainW2"], ["Lentimas chamber", "Lentimas_chamber_2"], ["Main chamber", "Main_chamber_4"], ["Mountainside", "Mountainside_2"], ["Main chamber (2)", "Main_chamber_5"], ["Basement chamber", "Basement_chamber_2"], ["Main chamber (3)", "Main_chamber_6"], ["Undella chamber", "Undella_chamber_2"], ["Undella Town", "Undella_Town"], ["The Billionaire", "The_Billionaire"], ["Marine Tube", "Marine_Tube"], ["Caitlin's villa", "Caitlin's_villa"], ["Funfest Mission", "Funfest_Mission"], ["Rival battle", "Rival_battle"], ["Undella Bay", "Undella_Bay"], ["Jellicent", "Jellicent"]],
  12: [["Route 13", "Route_13"], ["The Treasure Hunter", "The_Treasure_Hunter"], ["Cobalion is waiting", "Cobalion_is_waiting"], ["Lacunosa Town", "Lacunosa_Town"], ["The Old Legend", "The_Old_Legend"], ["The Businessman", "The_Businessman"], ["Zinzolin", "Zinzolin"], ["Route 12", "Route_12"], ["Hunt for Bug Pokémon", "Hunt_for_Bug_Pokémon"], ["Village Bridge", "Village_Bridge"], ["Rest Stop", "Rest_Stop"], ["Stonewall's Winning Streak", "Stonewall's_Winning_Streak"], ["The Voice", "The_Voice"], ["Route 11", "Route_11"], ["Virizion is waiting", "Virizion_is_waiting"]],
  13: [["Opelucid City", "Opelucid_City"], ["Reunite with Iris", "Reunite_with_Iris"], ["Get Props from the old man", "Get_Props_from_the_old_man"], ["The Tympole Choir", "The_Tympole_Choir"], ["Route 9", "Route_9"], ["Shopping Mall Nine", "Shopping_Mall_Nine"], ["Opelucid City (return)", "Opelucid_City_2"], ["Opelucid Gym", "Opelucid_Gym"], ["Drayden's Story", "Drayden's_Story"], ["Team Plasma Attacks!", "Team_Plasma_Attacks!"], ["Marine Tube", "Marine_Tube"], ["Humilau City", "Humilau_City"], ["Meet up with Hugh", "Meet_up_with_Hugh"], ["Move Tutor", "Move_Tutor"], ["Time for a Trade", "Time_for_a_Trade"], ["A New Funfest Mission", "A_New_Funfest_Mission"], ["Mienfoo's Daily Walk", "Mienfoo's_Daily_Walk"], ["Home is Where the Heart Scales Are", "Home_is_Where_the_Heart_Scales_Are"], ["Humilau Gym", "Humilau_Gym"], ["Route 22", "Route_22"], ["Terrakion is waiting", "Terrakion_is_waiting"], ["Return to Humilau", "Return_to_Humilau"]],
  14: [["Route 21", "Route_21"], ["Seaside Cave", "Seaside_Cave"], ["Route 21 (east)", "Route_21_(east)"], ["Plasma Frigate", "Plasma_Frigate"], ["North Entrance", "North_Entrance"], ["B1F (Black 2)", "B1FB2"], ["B1F (White 2)", "B1FW2"], ["Command Center", "Command_Center"], ["Giant Chasm", "Giant_Chasm"], ["Outer Cave", "Outer_Cave"], ["Crater Forest", "Crater_Forest"], ["Plasma Frigate (round 2)", "Plasma_Frigate_2"], ["Inner Cave", "Inner_Cave"]],
  15: [["Route 23", "Route_23"], ["East side", "East_side"], ["West side", "West_side"], ["Victory Road", "Victory_Road"], ["Entrance", "Entrance"], ["Victory Road (Black 2)", "Pokémon_Black_2"], ["Victory Road (White 2)", "Pokémon_White_2"], ["Northern path", "Northern_path"], ["Pokémon League", "Pokémon_League"], ["Left room: Shauntal", "Left_room:_Shauntal"], ["Center-left room: Grimsley", "Center-left_room:_Grimsley"], ["Center-right room: Caitlin", "Center-right_room:_Caitlin"], ["Right room: Marshal", "Right_room:_Marshal"], ["The Champion's Temple", "The_Champion's_Temple"]],
  16: [["Aspertia City", "Aspertia_City"], ["Home Again", "Home_Again"], ["Mass Outbreaks", "Mass_Outbreaks"], ["Floccesy Town", "Floccesy_Town"], ["New Wallpapers", "New_Wallpapers"], ["Alder's Challenge", "Alder's_Challenge"], ["Route 20", "Route_20"], ["Cave of Being", "Cave_of_Being"], ["Castelia City", "Castelia_City"], ["Game Freak", "Game_Freak"], ["Amanita's Gift", "Amanita's_Gift"], ["The Royal Unova", "The_Royal_Unova"], ["Nimbasa City", "Nimbasa_City"], ["Battle Institute", "Battle_Institute"], ["Big Stadium and Small Court", "Big_Stadium_and_Small_Court"], ["Battle Subway", "Battle_Subway"]],
  17: [["Pokémon World Tournament", "Pokémon_World_Tournament"], ["Clay Tunnel", "Clay_Tunnel"], ["Southern Cave", "Southern_Cave"], ["Western Cave", "Western_Cave"], ["Northern Cave", "Northern_Cave"], ["Southern Cave (2)", "Southern_Cave_2"], ["Eastern Cave", "Eastern_Cave"], ["Northern Cave (2)", "Northern_Cave_2"], ["Eastern Cave (2)", "Eastern_Cave_2"], ["Northern Cave (3)", "Northern_Cave_3"], ["Underground Ruins", "Underground_Ruins"], ["Twist Mountain", "Twist_Mountain"], ["B1F", "B1F"], ["1F", "1F"], ["2F", "2F"], ["3F", "3F"], ["Undella Town", "Undella_Town"], ["Cynthia, Champion of Sinnoh", "Cynthia,_Champion_of_Sinnoh"], ["Undella Bay", "Undella_Bay"], ["Abyssal Ruins", "Abyssal_Ruins"], ["Daily Battles against Hugh", "Daily_Battles_against_Hugh"]],
  18: [["Route 14", "Route_14"], ["Abundant Shrine", "Abundant_Shrine"], ["The Southeast", "The_Southeast"], ["Black City", "Black_City"], ["White Forest", "White_Forest"], ["Route 15", "Route_15"], ["Poké Transfer Lab", "Poké_Transfer_Lab"], ["Marvelous Bridge", "Marvelous_Bridge"], ["Cresselia", "Cresselia"], ["The Magikarp Salesman", "The_Magikarp_Salesman"]],
  19: [["Victory Road", "Victory_Road"], ["N's Castle", "N's_Castle"], ["1F", "1F"], ["2F", "2F"], ["Season battles", "Season_battles"], ["Opelucid City", "Opelucid_City"], ["Tubeline Bridge", "Tubeline_Bridge"], ["So Loud!", "So_Loud!"], ["Charge Ahead", "Charge_Ahead"], ["Route 8", "Route_8"], ["Moor of Icirrus", "Moor_of_Icirrus"], ["Icirrus City", "Icirrus_City"], ["The Ore Collector", "The_Ore_Collector"], ["Pokémon Fan Club", "Pokémon_Fan_Club"], ["Aha's Pep Quiz", "Aha's_Pep_Quiz"], ["The Shadows Reappear", "The_Shadows_Reappear"], ["Dragonspiral Tower", "Dragonspiral_Tower"], ["Giant Chasm", "Giant_Chasm"]],
  20: [["Skyarrow Bridge", "Skyarrow_Bridge"], ["The Salesman, The Runner", "The_Salesman,_The_Runner"], ["Pinwheel Forest", "Pinwheel_Forest"], ["Interior", "Interior"], ["Exterior", "Exterior"], ["Nacrene City", "Nacrene_City"], ["Café Warehouse", "Café_Warehouse"], ["Nacrene Museum", "Nacrene_Museum"], ["Move Tutor", "Move_Tutor"], ["Loblolly's Studio", "Loblolly's_Studio"], ["Get a Pokémon Egg", "Get_a_Pokémon_Egg"], ["Route 3", "Route_3"], ["Wellspring Cave", "Wellspring_Cave"], ["Preschool", "Preschool"], ["Pokémon Day Care", "Pokémon_Day_Care"], ["Striaton City", "Striaton_City"], ["Trainers' School", "Trainers'_School"], ["Pokémon Center", "Pokémon_Center"], ["Striaton Restaurant", "Striaton_Restaurant"], ["Funfest Mission", "Funfest_Mission"], ["Hints of a Legend", "Hints_of_a_Legend"], ["The Dreamyard", "The_Dreamyard"]],
  21: [["Route 2", "Route_2"], ["Accumula Town", "Accumula_Town"], ["The Northwest Building", "The_Northwest_Building"], ["The Northern Building", "The_Northern_Building"], ["The House on the Hill", "The_House_on_the_Hill"], ["The Southwest Building", "The_Southwest_Building"], ["Route 1", "Route_1"], ["Route 17 (south)", "Route_17_(south)"], ["Route 18", "Route_18"], ["Route 17 (north)", "Route_17_(north)"], ["P2 Laboratory, Plasma Frigate", "P2_Laboratory,_Plasma_Frigate"], ["Nuvema Town", "Nuvema_Town"], ["The Hero's House", "The_Hero's_House"], ["Cheren and Bianca's Homes", "Cheren_and_Bianca's_Homes"], ["Juniper Pokémon Lab", "Juniper_Pokémon_Lab"]],
  22: [["Reversal Mountain", "Reversal_Mountain"], ["Nature Preserve", "Nature_Preserve"], ["Pokémon League: Round 2", "Pokémon_League:_Round_2"], ["Shauntal", "Shauntal"], ["Grimsley", "Grimsley"], ["Caitlin", "Caitlin"], ["Marshal", "Marshal"], ["Champion Iris", "Champion_Iris"]],
};

const NOT_IN_GAME = [
  ["Tornadus / Thundurus / Landorus", "Pokémon Dream Radar (3DS app) only"],
  ["The other version's dragon & Lati", "Trade with the other version"],
  ["Victini, Keldeo, Meloetta, Genesect", "Event distributions only"],
];

/* ---------------------------------------------------------------------------
   Chapters & steps
--------------------------------------------------------------------------- */
const CHAPTERS = [
  /* ============================ PART 1 ============================ */
  {
    id: "p1", refs: [1], part: "Part 1", title: "A Starter & a Rival",
    areas: "Aspertia City · Route 19 · Floccesy Town",
    steps: [
      { id: "p1-home", ref: "1#Home", type: "story", loc: "Aspertia City", title: "Leave home and meet Hugh",
        text: "Mom says Professor Juniper's assistant Bianca is looking for you. Outside, your rival <b>Hugh</b> offers to help find her." },
      { id: "p1-starter", ref: "1#Aspertia_Outlook", type: "story", loc: "Aspertia City", title: "Aspertia Outlook: pick your starter from Bianca",
        text: "Climb the stairs on the north side of the city. Bianca asks you to help with the Pokédex, then lets you pick <b>Snivy, Tepig, or Oshawott</b>.",
        callout: "Set the <b>Starter</b> picker at the top of this page to match. Hugh's teams depend on it." },
      { id: "p1-hugh", ref: "1#Aspertia_Outlook", type: "boss", loc: "Aspertia City", title: "Rival battle: Hugh at the Outlook",
        boss: { who: "Rival Hugh", rival: true, team: [["$base", 5]],
          use: "An even fight. Just attack. Losing costs you nothing.", reward: "" } },
      { id: "p1-center", ref: "1#Pokémon_Center", type: "story", loc: "Aspertia City", title: "Pokémon Center tour, then head north",
        text: "Bianca shows you the Pokémon Center and gives you <b>10 Poké Balls</b>. Outside, Mom gives you the <b>Running Shoes</b>, and Hugh's sister gives you a <b>Town Map</b> plus a spare one to deliver to Hugh. Go north through the gate." },
      { id: "p1-route19", ref: "1#Route_19", type: "story", loc: "Route 19", title: "Route 19: catching lesson, then follow Alder",
        text: "Bianca shows you how to catch a Pokémon. Farther east, <b>Alder</b> jumps down from the cliff and leads you to Floccesy Town." },
      { id: "p1-floccesy", ref: "1#Floccesy_Town", type: "story", loc: "Floccesy Town", title: "Floccesy Town: Alder says Hugh went to Route 20",
        text: "" },
    ],
  },

  /* ============================ PART 2 ============================ */
  {
    id: "p2", refs: [2], part: "Part 2", title: "Floccesy Ranch & Cheren",
    areas: "Route 20 · Floccesy Ranch · Pledge Grove · Aspertia Gym",
    badge: "Basic Badge (#1)",
    steps: [
      { id: "p2-route20", ref: "2#Route_20", type: "story", loc: "Route 20", title: "Route 20: cross the bridge and go north to Floccesy Ranch",
        text: "A Hiker blocks the east stairs for now." },
      { id: "p2-hugh", ref: "2#Floccesy_Ranch", type: "boss", loc: "Floccesy Ranch", title: "Rival battle: Hugh at the ranch pastures",
        boss: { who: "Rival Hugh", rival: true, team: [["$base", 8]],
          use: "Still an even fight. Keep your starter healthy.", reward: "" } },
      { id: "p2-herdier", ref: "2#Floccesy_Ranch", type: "story", loc: "Floccesy Ranch", title: "Find the ranch owner's lost Herdier",
        text: "Give Hugh the spare Town Map. Search the forest north of the pastures: go east, then south to a clearing, where a <b>Team Plasma Grunt</b> has Herdier cornered. The Grunt runs off." },
      { id: "p2-alder", ref: "2#Alder's_house", type: "boss", loc: "Floccesy Town", title: "Floccesy Town: battle Alder's two students",
        text: "Back at Alder's house. Their Pokémon depend on your starter. Afterward, Mr. Medal gives you the Medal Box, and Alder says the Aspertia Gym has reopened." },
      { id: "p2-pledge", ref: "2#Pledge_Grove", type: "tip", loc: "Floccesy Town", title: "Pledge Grove (behind Alder's house): skip it",
        text: "It only matters for Keldeo, which is event-only." },
      { id: "p2-gym", ref: "2#Trainers'_School", type: "boss", loc: "Aspertia City", title: "Aspertia Gym: Cheren",
        text: "Go through the Trainers' School and out the back door to the Gym.",
        boss: { who: "Gym Leader Cheren", team: [["Patrat", 11, "Normal"], ["Lillipup", 13, "Normal"]],
          use: "<b>Fighting</b>. A Riolu from Floccesy Ranch is great here. Both know Work Up, so KO them fast, or use Growl to cancel it.", reward: "Basic Badge + TM83 Work Up" } },
      { id: "p2-after", ref: "2#Route_20_2", type: "story", loc: "Route 20", title: "Head east over Route 20 to Virbank City",
        text: "Outside the Gym, Bianca gives you TM27 Return and the C-Gear. In Floccesy she adds the Habitat List to your Pokédex. At the Route 20 stairs, Cheren gives you <b>Pecha Berries</b> (they cure poison) for the next Gym." },
    ],
  },

  /* ============================ PART 3 ============================ */
  {
    id: "p3", refs: [3], part: "Part 3", title: "Roxie & Virbank City",
    areas: "Virbank City · Virbank Complex · Virbank Gym · Pokéstar Studios",
    badge: "Toxic Badge (#2)",
    steps: [
      { id: "p3-arrive", ref: "3#Virbank_City", type: "story", loc: "Virbank City", title: "Virbank City: Roxie argues with her father",
        text: "Near the Pokémon Center. Her dad runs the ferry to Castelia but quits to become an actor." },
      { id: "p3-complex", ref: "3#Virbank_Complex", type: "tip", loc: "Virbank City", title: "Virbank Complex: Magnemite + TM94 Rock Smash",
        text: "Catch a <b>Magnemite</b> there. As a Steel type it can't be poisoned, which helps a lot at Roxie's Gym. Beat the three new Workers for Rock Smash." },
      { id: "p3-gym", ref: "3#Virbank_Gym", type: "boss", loc: "Virbank City", title: "Virbank Gym: Roxie",
        text: "Beat Nicky and Billy Jo to stop the music, then challenge Roxie. Bring <b>Antidotes</b>.",
        boss: { who: "Gym Leader Roxie", team: [["Koffing", 16, "Poison"], ["Whirlipede", 18, "Bug/Poison"]],
          use: "Psychic or Ground. Fire and Flying also hit Whirlipede. Cure poison fast, because Venoshock hits poisoned targets twice as hard.", reward: "Toxic Badge + TM09 Venoshock" } },
      { id: "p3-studios", ref: "3#Pokéstar_Studios", type: "story", loc: "Virbank City", title: "Pokéstar Studios: watch Pop Roxie's movie and film one",
        text: "A scout from the studio takes you north of town. Watch Roxie's dad's movie, then shoot a scene with Brycen." },
      { id: "p3-pier", ref: "3#Team_Plasma_Appears", type: "boss", loc: "Virbank City", title: "Team Plasma at the Virbank pier",
        text: "Roxie and Hugh are facing down Team Plasma. Talk to the Grunt in the middle. Afterward Roxie gives you <b>HM01 Cut</b>." },
      { id: "p3-route20", ref: "3#Route_20", type: "boss", loc: "Route 20", title: "Chase the last Grunt onto Route 20",
        text: "Climb the center stairway on Route 20 and head south. She's hiding in a small clearing just off the path." },
      { id: "p3-ship", ref: "3#Virbank_City_3", type: "story", loc: "Virbank City", title: "Take the ferry to Castelia City with Hugh",
        text: "Pop Roxie is back at work. Go into the pier building and board the ship with Hugh." },
    ],
  },

  /* ============================ PART 4 ============================ */
  {
    id: "p4", refs: [4], part: "Part 4", title: "Burgh & Castelia City",
    areas: "Castelia City · Castelia Sewers · Castelia Gym",
    badge: "Insect Badge (#3)",
    steps: [
      { id: "p4-arrive", ref: "4#Oceanfront_Road", type: "story", loc: "Castelia City", title: "Castelia City: get the Bicycle on Oceanfront Road",
        text: "Hugh registers you on his Xtransceiver. The Harlequin on Oceanfront Road gives you a <b>Bicycle</b>." },
      { id: "p4-company", ref: "4#Oceanfront_Road", type: "tip", loc: "Castelia City", title: "Battle Company: Exp. Share, Quick and Timer Balls",
        text: "The Janitor on 1F gives you an <b>Exp. Share</b>. Beat the Clerks on 47F for Quick Balls and 5 Timer Balls." },
      { id: "p4-iris", ref: "4#Gym_Street", type: "story", loc: "Castelia City", title: "Gym Street: Burgh is out, so follow Iris to the sewers",
        text: "Iris leads you east along Oceanfront Road to <b>Thumb Pier</b>, where you go into the Castelia Sewers after Hugh." },
      { id: "p4-hugh", ref: "4#Castelia_Sewers", type: "boss", loc: "Castelia City", title: "Rival battle: Hugh in the sewers",
        boss: { who: "Rival Hugh", rival: true, team: [["$mid", 20], ["Pidove", 18, "Normal/Flying"]],
          use: "Electric, Rock, or Ice for Pidove. For his starter, use whatever beats it.", reward: "" } },
      { id: "p4-sewers", ref: "4#Castelia_Sewers", type: "story", loc: "Castelia City", title: "Sewers: tag battle two Grunts with Hugh",
        text: "Hugh heals you after every battle while he tags along. At the end of the walkway, beat the two Grunts in a Double Battle. The route depends on the month (the water level changes): in <b>Jan, Feb, May, Jun, Sep, or Oct</b>, walk north over the water and turn left. In the other months, head west and climb the north stairs. Hugh gives you <b>HM04 Strength</b>. Burgh and Colress show up, then you head back out to the Gym." },
      { id: "p4-gym", ref: "4#Castelia_Gym", type: "boss", loc: "Castelia City", title: "Castelia Gym: Burgh",
        text: "The cocoons teleport you, and which way you face when entering changes where you go. Beat Harlequin Gary, enter the east cocoon from its <b>right</b> side, beat Anders, then enter the next cocoon from its <b>left</b> side.",
        boss: { who: "Gym Leader Burgh", team: [["Swadloon", 22, "Bug/Grass"], ["Dwebble", 22, "Bug/Rock"], ["Leavanny", 24, "Bug/Grass", "Sitrus Berry"]],
          use: "<b>Fire or Flying</b> (4× on Swadloon and Leavanny). Use Water or Rock on Dwebble.", reward: "Insect Badge + TM76 Struggle Bug" } },
      { id: "p4-colress", ref: "4#Central_Plaza", type: "story", loc: "Castelia City", title: "Central Plaza: Colress challenges you, then head north to Route 4",
        text: "He'll wait for you on Route 4." },
    ],
  },

  /* ============================ PART 5 ============================ */
  {
    id: "p5", refs: [5], part: "Part 5", title: "Route 4 & Join Avenue",
    areas: "Route 4 · Desert Resort · Relic Castle · Join Avenue",
    steps: [
      { id: "p5-dowsing", ref: "5#{Route_4B2|Route_4W2}", type: "story", loc: "Route 4", title: "Castelia Gate: Bianca gives you the Dowsing MCHN",
        text: "It finds hidden items nearby." },
      { id: "p5-colress", ref: "5#{Challenge_Colress|Challenge_Colress_2}", type: "boss", loc: "Route 4", title: "Route 4: battle Colress",
        text: "He wakes up the Crustle blocking the road, then battles you.",
        boss: { who: "Colress", team: [["Magnemite", 21, "Electric/Steel"], ["Klink", 23, "Steel"]],
          use: "<b>Ground</b> (4× on Magnemite), Fire, Fighting.", reward: "Protein" } },
      { id: "p5-heal", ref: "5#{Rest_House|Rest_House_2}", type: "heal", loc: "Route 4", title: "Route 4 rest house: the woman inside heals you",
        text: "{Go west along the new paved road.|It's the small building east of PokéFan Sachiko.}" },
      { id: "p5-desert", ref: "5#Desert_Resort", type: "tip", loc: "Desert Resort", title: "Desert Resort & Relic Castle: optional",
        text: "These are only for items. Nurse Mariah in the southeast of the desert heals you after you beat her. A <b>Sandile or Sandshrew</b> from here is great against Elesa's Gym." },
      { id: "p5-join", ref: "5#Join_Avenue", type: "story", loc: "Join Avenue", title: "Join Avenue: become the manager, then go north to Nimbasa City",
        text: "Join Avenue is north of Route 4. Accept the owner's request and pick your phrases. Then keep going north to Nimbasa City." },
    ],
  },

  /* ============================ PART 6 ============================ */
  {
    id: "p6", refs: [6], part: "Part 6", title: "Elesa & Nimbasa City",
    areas: "Nimbasa City · Nimbasa Gym · Anville Town · Route 16 · Lostlorn Forest",
    badge: "Bolt Badge (#4)",
    steps: [
      { id: "p6-subway", ref: "6#Pair_up_against_the_Subway_Bosses", type: "boss", loc: "Nimbasa City", title: "Tag battle vs. the Subway Bosses outside Gear Station",
        text: "Talk to the Trainer in front of Ingo and Emmet. You team up with Rosa or Nate.",
        boss: { who: "Ingo & Emmet (multi)", team: [["Gurdurr", 26, "Fighting"], ["Boldore", 26, "Rock"]],
          use: "Psychic or Flying for Gurdurr. Water, Grass, or Fighting for Boldore.", reward: "Vs. Recorder" } },
      { id: "p6-gym", ref: "6#Amusement_Park", type: "boss", loc: "Nimbasa City", title: "Nimbasa Gym (east of the Ferris wheel): Elesa",
        boss: { who: "Gym Leader Elesa", team: [["Emolga", 28, "Electric/Flying"], ["Flaaffy", 28, "Electric"], ["Zebstrika", 30, "Electric", "Sitrus Berry"]],
          use: "<b>Ground</b> for Flaaffy and Zebstrika. Emolga is immune to Ground, so use Rock or Ice on it. Sandile and Sandshrew are immune to her Electric moves.", reward: "Bolt Badge + TM72 Volt Switch" } },
      { id: "p6-plasma", ref: "6#Hugh_and_Team_Plasma_face_off", type: "boss", loc: "Nimbasa City", title: "Help Hugh against Team Plasma outside Big Stadium",
        text: "Afterward Hugh explains that Team Plasma stole his little sister's Purrloin. He heals your party, then runs off." },
      { id: "p6-side", ref: "6#Anville_Town", type: "tip", loc: "Nimbasa City", title: "Anville Town, Route 16, Lostlorn Forest: optional",
        text: "Side areas only. The Marvelous Bridge elevator on Route 16 stays broken until after the Hall of Fame." },
      { id: "p6-west", ref: "6#Route_16", type: "story", loc: "Route 5", title: "Head west out of Nimbasa onto Route 5", text: "" },
    ],
  },

  /* ============================ PART 7 ============================ */
  {
    id: "p7", refs: [7], part: "Part 7", title: "Clay & Driftveil City",
    areas: "Route 5 · Driftveil Drawbridge · Driftveil City · Driftveil Gym",
    badge: "Quake Badge (#5)",
    steps: [
      { id: "p7-fly", ref: "7#Bianca's_HM", type: "story", loc: "Route 5", title: "Route 5: Bianca gives you HM02 Fly",
        text: "She also shows you a <b>Hidden Grotto</b>, which has a Minccino with its Hidden Ability." },
      { id: "p7-charles", ref: "7#Roadblock", type: "boss", loc: "Route 5", title: "Motorcyclist Charles blocks the drawbridge",
        text: "It's a {Rotation|Triple} Battle, so check your party order first.",
        boss: { who: "Motorcyclist Charles", team: [["Sigilyph", 26, "Psychic/Flying"], ["Archen", 26, "Rock/Flying"], ["Tirtouga", 26, "Water/Rock"]],
          use: "<b>Electric</b> hits all three. Grass is 4× on Tirtouga.", reward: "" } },
      { id: "p7-city", ref: "7#Team_Plasma,_Old_&_New", type: "story", loc: "Driftveil Drawbridge", title: "Cross the Driftveil Drawbridge into Driftveil City",
        text: "A former Plasma member is arguing with a current one. He invites you to their old base on the hill <b>west of the Gym</b>." },
      { id: "p7-rood", ref: "7#Former_Plasma_Base", type: "boss", loc: "Driftveil City", title: "Former Plasma base: battle Rood",
        text: "Afterward he explains the old Team Plasma's change of heart and gives you a <b>Zorua</b> that once traveled with N.",
        boss: { who: "Rood", team: [["Herdier", 27, "Normal"], ["Swoobat", 27, "Psychic/Flying"]],
          use: "Fighting for Herdier. Electric, Rock, or Ice for Swoobat.", reward: "" } },
      { id: "p7-tutor", ref: "7#Move_Tutor", type: "tip", loc: "Driftveil City", title: "Move Tutor (pays in Red Shards): Ice Punch or Seed Bomb",
        text: "He's in the house next to the Chateau Hotel. Both moves are good against Clay." },
      { id: "p7-gym", ref: "7#Driftveil_Gym", type: "boss", loc: "Driftveil City", title: "Driftveil Gym: Clay",
        text: "Ride the conveyor belts through the dark mine to Clay in the northeast.",
        boss: { who: "Gym Leader Clay", team: [["Krokorok", 31, "Ground/Dark"], ["Sandslash", 31, "Ground"], ["Excadrill", 33, "Ground/Steel", "Sitrus Berry"]],
          use: "<b>Water</b> hits all three. Grass works on Krokorok and Sandslash, and Fighting on Krokorok and Excadrill. Bulldoze lowers your Speed.", reward: "Quake Badge + TM78 Bulldoze" } },
      { id: "p7-pwt", ref: "7#Driftveil_Gym", type: "story", loc: "Pokémon World Tournament", title: "Follow Hugh south to the Pokémon World Tournament", text: "" },
    ],
  },

  /* ============================ PART 8 ============================ */
  {
    id: "p8", refs: [8], part: "Part 8", title: "World Tournament & the Plasma Frigate",
    areas: "Pokémon World Tournament · Plasma Frigate · Relic Passage",
    steps: [
      { id: "p8-register", ref: "8#World_Tournament_building", type: "story", loc: "Pokémon World Tournament", title: "Register for the Driftveil Tournament",
        text: "You can't use items during the tournament, so give your Pokémon <b>held items before registering</b>. You need three wins in a row." },
      { id: "p8-hugh", ref: "8#World_Tournament_building", type: "boss", loc: "Pokémon World Tournament", title: "Round 1: Hugh",
        boss: { who: "Rival Hugh", rival: true, team: [["$mid", 25, "", "-"], ["$monkey", 25, "", "-"], ["Tranquill", 25, "Normal/Flying"]],
          use: "Electric, Rock, or Ice for Tranquill. For the other two, use whatever beats his starter.", reward: "" } },
      { id: "p8-cheren", ref: "8#World_Tournament_building", type: "boss", loc: "Pokémon World Tournament", title: "Round 2: Cheren",
        boss: { who: "Cheren", team: [["Stoutland", 25, "Normal"], ["Cinccino", 25, "Normal"], ["Watchog", 25, "Normal"]],
          use: "<b>Fighting</b>.", reward: "" } },
      { id: "p8-colress", ref: "8#World_Tournament_building", type: "boss", loc: "Pokémon World Tournament", title: "Final: Colress",
        boss: { who: "Colress", team: [["Magneton", 25, "Electric/Steel"], ["Elgyem", 25, "Psychic"], ["Klink", 25, "Steel"]],
          use: "Ground (4× on Magneton) and Fire. Use Dark, Bug, or Ghost on Elgyem.", reward: "1 BP" } },
      { id: "p8-frigate", ref: "8#Plasma_Frigate", type: "story", loc: "Pokémon World Tournament", title: "Storm the Plasma Frigate at the pier with Hugh and Cheren",
        text: "Team Plasma walks past outside. <b>Heal up</b>, then follow Hugh south to the pier. Beat the first two Grunts on your own, then tag-battle the rest with Cheren and then Hugh. Zinzolin shows up, and the Shadow Triad teleports you off the ship. Cheren heads for Route 6." },
      { id: "p8-relic", ref: "8#Relic_Passage", type: "tip", loc: "Pokémon World Tournament", title: "Relic Passage & Relic Castle: optional",
        text: "These are only for items and shards. Volcarona at the bottom of Relic Castle is strong but not a legendary." },
    ],
  },

  /* ============================ PART 9 ============================ */
  {
    id: "p9", refs: [9], part: "Part 9", title: "Route 6 & Chargestone Cave",
    areas: "Route 6 · Mistralton Cave · Chargestone Cave",
    steps: [
      { id: "p9-surf", ref: "9#Meet_up_with_Cheren", type: "story", loc: "Route 6", title: "Route 6: Cheren gives you HM03 Surf",
        text: "Go west from Driftveil. Cheren is outside the Season Research Lab." },
      { id: "p9-cobalion", ref: "9#A_Legendary_Pokémon_Appears", type: "story", loc: "Route 6", title: "Westernmost bridge: Cobalion appears, then runs off",
        text: "Rood shows up and says it would be a great ally.",
        callout: "You can catch <b>Cobalion</b> on Route 13 in Part 12." },
      { id: "p9-heal", ref: "9#A_Legendary_Pokémon_Appears", type: "heal", loc: "Route 6", title: "The woman in the house east of the bridge heals you", text: "" },
      { id: "p9-mcave", ref: "9#Mistralton_Cave", type: "tip", loc: "Mistralton Cave", title: "Mistralton Cave: optional (TM80 Rock Slide)",
        text: "Surf east along the river. You need Flash and Strength. An old man inside tells the story of the Swords of Justice." },
      { id: "p9-chargestone", ref: "9#Chargestone_Cave", type: "story", loc: "Chargestone Cave", title: "Chargestone Cave: push the floating stones",
        text: "Head north on Route 6. The floating stones stick to the blue boulders when pushed." +
          "<ol><li><b>1F:</b> Bianca explains the stones. Push the first one <b>left</b> and the next one <b>right</b>, keep east, then go south across the bridge. Beat Ace Trainer Corky (Triple Battle) and take the stairs down.</li>" +
          "<li><b>B1F:</b> Go west, then north. Doctor Kit heals you after you beat him. Weave around the blue boulders to Bianca, then take the <b>west</b> stairs down.</li>" +
          "<li><b>B2F:</b> Go south past Guitarist Beverly, then take the stairs back up.</li>" +
          "<li><b>B1F:</b> Go east past Bianca and up the stairs.</li>" +
          "<li><b>1F:</b> Go south, then east to the exit into <b>Mistralton City</b>. You've reached Part 10.</li></ol>" },
    ],
  },

  /* ============================ PART 10 ============================ */
  {
    id: "p10", refs: [10], part: "Part 10", title: "Skyla & the Celestial Tower",
    areas: "Mistralton City · Route 7 · Celestial Tower · Mistralton Gym",
    badge: "Jet Badge (#6)",
    steps: [
      { id: "p10-master", ref: "10#Meet_Professor_Juniper_and_Skyla", type: "key", loc: "Mistralton City", title: "Get the Master Ball from Professor Juniper",
        text: "Walk north past the Pokémon Center. Juniper stops you and hands over a <b>Master Ball</b>. Skyla shows up, then Juniper heads off to Celestial Tower.",
        callout: "Hold onto it. <b>Kyurem</b> (post-game) is the best use for it." },
      { id: "p10-route7", ref: "10#Route_7", type: "story", loc: "Route 7", title: "Head north up Route 7 to Celestial Tower",
        text: "Use the raised walkways to skip most of the tall grass." },
      { id: "p10-tower", ref: "10#Celestial_Tower", mapPin: [73.8, 61.3], mapLabel: "The bell (roof)", type: "story", loc: "Celestial Tower", map: "celestial-tower", title: "Climb Celestial Tower and ring the bell",
        text: "Juniper is on 1F and gives you a <b>Lucky Egg</b>. Climb all five floors to the roof and ring the bell.",
        callout: "You come back here after the Hall of Fame to catch <b>Mesprit</b> at the foot of the bell platform." },
      { id: "p10-heal", ref: "10#Celestial_Tower", type: "heal", loc: "Celestial Tower", title: "Nurse Dixie on 3F heals your party after you beat her",
        text: "Wild Litwick can burn you with Flame Body. Use her as a free Pokémon Center." },
      { id: "p10-twist", ref: "10#Twist_Mountain", type: "tip", loc: "Twist Mountain", title: "Twist Mountain is blocked, so skip it",
        text: "Marshal blocks the entrance at the northeast end of Route 7. There's nothing to do here yet." },
      { id: "p10-gym", ref: "10#Mistralton_Gym", type: "boss", loc: "Mistralton City", title: "Mistralton Gym: Skyla",
        text: "The turbines blow you back to the entrance. Move while the wind is off and duck behind the walls when it starts.",
        boss: { who: "Gym Leader Skyla", team: [["Swoobat", 37, "Psychic/Flying"], ["Skarmory", 37, "Steel/Flying"], ["Swanna", 39, "Water/Flying", "Sitrus Berry"]],
          use: "Electric hits all three (4× on Swanna). Rock also works on Swoobat and Swanna. Use Fire or Electric on Skarmory.", reward: "Jet Badge + TM62 Acrobatics" } },
      { id: "p10-cargo", ref: "10#Mistralton_Cargo_Service_2", type: "story", loc: "Mistralton City", title: "Go to the Cargo Service building and talk to Skyla",
        text: "Juniper meets you outside the Gym. Go into Cargo Service and talk to Skyla. Bianca joins, and Skyla flies the group to <b>Lentimas Town</b>." },
    ],
  },

  /* ============================ PART 11 ============================ */
  {
    id: "p11", refs: [11], part: "Part 11", title: "Lunar Wing & Reversal Mountain",
    areas: "Lentimas Town · Strange House · Reversal Mountain · Undella Town",
    steps: [
      { id: "p11-lentimas", ref: "11#Juniper_Tells_a_Story", type: "story", loc: "Lentimas Town", title: "Listen to Juniper in Lentimas Town",
        text: "She sends you to Opelucid City to ask Drayden about the legendary dragons. To get there, head east through Reversal Mountain." },
      { id: "p11-tutor", ref: "11#Move_Tutor", type: "tip", loc: "Lentimas Town", title: "Move Tutor (pays in Blue Shards): Icy Wind / Dragon Pulse",
        text: "Lives in the west house. Ice and Dragon moves are good against Drayden, two gyms from now." },
      { id: "p11-lunar", ref: "11#Strange_House", type: "key", loc: "Strange House", title: "Get the Lunar Wing from the Strange House (needed for Cresselia)",
        text: "The Strange House is hidden in the canyon east of Lentimas. Furniture blocks most paths, so follow this loop:" +
          "<ol><li>Entrance hall: go <b>left</b>, take the stairs <b>down</b> to B1F.</li>" +
          "<li>B1F: take the <b>east</b> stairs back up.</li>" +
          "<li>Climb to the upper level, go west, loop around to the lower-west room, take the <b>west</b> stairs down.</li>" +
          "<li>B1F: follow the new path east and go back up.</li>" +
          "<li>Take the <b>east</b> staircase, then the <b>center</b> staircase. The room at the top has the <b>Lunar Wing</b>.</li></ol>",
        callout: "Nothing in the story needs this, but you can't get <b>Cresselia</b> without it. You're right next to it now." },
      { id: "p11-reversal", ref: "11#{Reversal_MountainB2|Reversal_MountainW2}", mapPin: { b2: [48.1, 28.7], w2: [48.1, 76.4] }, mapLabel: "Exit to Undella Town", type: "story", loc: "Reversal Mountain", map: "reversal-mountain", title: "Cross Reversal Mountain with Bianca",
        text: "Bianca tags along and heals you between battles. The exit is the <b>Undella chamber</b> at the far east end of the main chamber." +
          "{<p><b>Black 2:</b> Main chamber → south → exit southwest to the mountainside and come back in. Head east past the stairway Bianca wants to check. Keep east past Ace Trainers Ray & Cora and the Scientist, then exit east.</p>|<p><b>White 2:</b> Main chamber → south to Battle Girl Chan → out the southwest exit and back in. Head east past the stairway Bianca wants to check. Go down near Black Belt Corey, then make your way east past Ace Trainers Ray & Cora and the Scientist, then exit east.</p>}",
        callout: "Bianca's \"Heatran chamber\" on B1F is where <b>Heatran</b> appears post-game, once you have the Magma Stone." },
      { id: "p11-falseswipe", ref: "11#{Reversal_MountainB2|Reversal_MountainW2}", type: "tip", loc: "Reversal Mountain", title: "TM54 False Swipe (Scientist, needs a full Habitat List)",
        text: "The Scientist east of Ace Trainers Ray & Cora gives you False Swipe if you've seen every Pokémon on the local Habitat List. It leaves targets at 1 HP, which makes legendaries much easier to catch." },
      { id: "p11-hugh", ref: "11#Rival_battle", type: "boss", loc: "Undella Town", title: "Rival battle: Hugh at the Undella gate",
        text: "Hugh catches you as you walk toward the north gate.",
        boss: { who: "Rival Hugh", rival: true, team: [["Unfezant", 39, "Normal/Flying", "Scope Lens"], ["$monkey", 39], ["$ace", 41]],
          use: "Electric, Rock, or Ice for Unfezant. For the other two, use whatever beats his starter.", reward: "" } },
    ],
  },

  /* ============================ PART 12 ============================ */
  {
    id: "p12", refs: [12], part: "Part 12", title: "Two Swords of Justice",
    areas: "Route 13 · Lacunosa Town · Route 12 · Village Bridge · Route 11",
    steps: [
      { id: "p12-prep", ref: "12#Route_13", type: "prep", loc: "Undella Town", title: "Stock up on balls before Route 13",
        text: "You're about to meet two Lv45 legendaries with very low catch rates. Bring <b>15+ Ultra Balls</b>, plus Quick, Timer, or Dusk Balls if you have them. <b>Dusk Balls work at night outdoors too.</b> Bring something that can <b>Sleep or Paralyze</b>, and <b>False Swipe</b> if you have it.<br>" +
              "Save before each fight. If you KO one by accident, reload, or catch it at Lv65 after the Hall of Fame." },
      { id: "p12-cobalion", ref: "12#Cobalion_is_waiting", type: "legend", legend: "cobalion", loc: "Route 13", title: "Cobalion: Route 13 clearing (Lv45)",
        text: "Head north along the beach. Climb the stairway into the forest and walk toward the Cut trees. Cobalion is waiting in the clearing.",
        tactic: "Open with Fire, Fighting, or Ground. Finish off with neutral moves. Never use Dark moves." },
      { id: "p12-lacunosa", ref: "12#The_Old_Legend", type: "story", loc: "Lacunosa Town", title: "Lacunosa Town: hear the Giant Chasm legend",
        text: "Juniper and Bianca take you to an old woman on the north side of town. She tells the story of the monster from the Giant Chasm (Kyurem)." },
      { id: "p12-zinzolin", ref: "12#Zinzolin", type: "boss", loc: "Lacunosa Town", title: "Tag battle: you + Hugh vs. Zinzolin + Grunt",
        text: "Head west from the Pokémon Center. Zinzolin and a Grunt show up, and Hugh asks you to team up.",
        boss: { who: "Zinzolin & Plasma Grunt (double)", team: [["Cryogonal", 42, "Ice"], ["Sneasel", 44, "Dark/Ice"], ["Golbat", 39, "Poison/Flying"], ["Garbodor", 39, "Poison"]],
          use: "Fire, Fighting, Rock, or Steel for the Ice types. Psychic or Ground for Garbodor.", reward: "" } },
      { id: "p12-route12", ref: "12#Route_12", type: "story", loc: "Route 12", title: "West through Route 12 and Village Bridge",
        text: "This is a short route." },
      { id: "p12-heal", ref: "12#Rest_Stop", type: "heal", loc: "Village Bridge", title: "Village Bridge: the woman in the easternmost house heals you",
        text: "There's no Pokémon Center nearby. Heal here before Virizion." },
      { id: "p12-virizion", ref: "12#Virizion_is_waiting", type: "legend", legend: "virizion", loc: "Route 11", title: "Virizion: west end of Route 11 (Lv45)",
        text: "Walk to the west side of Route 11 and Virizion jumps down from the cliff.",
        tactic: "Flying hits it 4×. Fire, Ice, and Psychic are also strong. Never use Dark moves." },
      { id: "p12-opelucid", ref: "12#Route_11", type: "story", loc: "Route 11", title: "Keep west to Opelucid City", text: "" },
    ],
  },

  /* ============================ PART 13 ============================ */
  {
    id: "p13", refs: [13], part: "Part 13", title: "Drayden, Marlon & Terrakion",
    areas: "Opelucid City · Route 9 · Opelucid Gym · Marine Tube · Humilau City · Route 22",
    badge: "Legend Badge (#7) · Wave Badge (#8)",
    steps: [
      { id: "p13-iris", ref: "13#Reunite_with_Iris", type: "story", loc: "Opelucid City", title: "Iris greets you and points you to the Gym", text: "" },
      { id: "p13-mall", ref: "13#Shopping_Mall_Nine", type: "prep", loc: "Route 9", title: "Shopping Mall Nine (Route 9): buy your legendary ball stock here",
        text: "This mall has the best ball selection in the game: <b>Ultra, Dusk, Timer, Quick, Repeat</b>. Buy lots of <b>Dusk Balls</b>, since most post-game legendaries are in caves. Buy Timer Balls for long fights." },
      { id: "p13-gym", ref: "13#Opelucid_Gym", type: "boss", loc: "Opelucid City", title: "Opelucid Gym: Drayden",
        text: "Beat Veteran Lucius to raise the first dragon statue. Then beat <b>one</b> Trainer on each of the next two levels. The statues butt heads and open a path to Drayden.",
        boss: { who: "Gym Leader Drayden", team: [["Druddigon", 46, "Dragon"], ["Flygon", 46, "Ground/Dragon"], ["Haxorus", 48, "Dragon", "Sitrus Berry"]],
          use: "<b>Ice</b> (4× on Flygon) and Dragon. Grass, Fire, Water, and Electric are all resisted. KO Haxorus before Dragon Dance snowballs.", reward: "Legend Badge + TM82 Dragon Tail" } },
      { id: "p13-attack", ref: "13#Team_Plasma_Attacks!", type: "story", loc: "Opelucid City", title: "Team Plasma freezes the city: beat 3 Grunts",
        text: "After Drayden's story, the Plasma Frigate attacks. Slide across the ice and beat the three Grunts:" +
          "<ol><li>Just east of the Pokémon Center</li><li>North, outside the old Battle House</li><li>South of the Gym</li></ol>Then go back to the Gym." },
      { id: "p13-zinzolin", ref: "13#Team_Plasma_Attacks!", type: "boss", loc: "Opelucid City", title: "Zinzolin at the Gym",
        text: "",
        boss: { who: "Zinzolin", team: [["Cryogonal", 46, "Ice"], ["Cryogonal", 46, "Ice"], ["Weavile", 48, "Dark/Ice"]],
          use: "Fire and Fighting. Fighting is 4× on Weavile.", reward: "" } },
      { id: "p13-shadow", ref: "13#Team_Plasma_Attacks!", type: "boss", loc: "Route 11", title: "Shadow Triad member at the Route 11 gate",
        text: "A Shadow steals the DNA Splicers. One of them waits south near the Route 11 gate.",
        boss: { who: "Shadow Triad", team: [["Pawniard", 46, "Dark/Steel"], ["Pawniard", 46, "Dark/Steel"], ["Absol", 48, "Dark"]],
          use: "<b>Fighting</b> (4× on Pawniard).", reward: "" } },
      { id: "p13-tube", ref: "13#Marine_Tube", type: "story", loc: "Marine Tube", title: "Fly back to Undella Town and take the Marine Tube to Humilau City",
        text: "Cheren says Team Plasma is near Humilau." },
      { id: "p13-marlon", ref: "13#Meet_up_with_Hugh", type: "story", loc: "Humilau City", title: "Meet Hugh, then walk north until Marlon jumps onto the pier",
        text: "After that, Marlon goes back to his Gym." },
      { id: "p13-gym2", ref: "13#Humilau_Gym", type: "boss", loc: "Humilau City", title: "Humilau Gym: Marlon",
        text: "Stepping on a lily pad slides it until it hits something. Ride the pads <b>clockwise</b> from dock to dock: SW dock → east → south → around the east wall → NW dock. Do the clockwise loop again to reach Marlon. You only need to fight the Ace Trainers in your way.",
        boss: { who: "Gym Leader Marlon", team: [["Carracosta", 49, "Water/Rock"], ["Wailord", 49, "Water"], ["Jellicent", 51, "Water/Ghost", "Sitrus Berry"]],
          use: "<b>Grass</b> (4× on Carracosta) and Electric. All three know Scald (burns). Carracosta has Sturdy and Shell Smash.", reward: "Wave Badge + TM55 Scald" } },
      { id: "p13-prep", ref: "13#Humilau_Gym", type: "prep", loc: "Humilau City", title: "Restock Ultra Balls: Terrakion is next door", text: "" },
      { id: "p13-terrakion", ref: "13#Terrakion_is_waiting", type: "legend", legend: "terrakion", loc: "Route 22", title: "Terrakion: center of Route 22 (Lv45)",
        text: "As you walk up, Colress cuts in and gives you the <b>Colress MCHN</b>. Then you can fight Terrakion.",
        tactic: "Water, Grass, Fighting, Ground, Psychic, and Steel all do 2×. Never use Dark moves." },
      { id: "p13-boulder", ref: "13#Return_to_Humilau", type: "story", loc: "Route 22", title: "Push the Strength boulder southeast to make a shortcut, then go back to Humilau",
        text: "Grunts block the Giant Chasm for now. Colress tells you to check <b>Seaside Cave</b> on Route 21." },
    ],
  },

  /* ============================ PART 14 ============================ */
  {
    id: "p14", refs: [14], part: "Part 14", title: "The Plasma Frigate & Giant Chasm",
    areas: "Route 21 · Seaside Cave · Plasma Frigate · Giant Chasm",
    steps: [
      { id: "p14-seaside", map: ["seaside-cave-1f", "seaside-cave-b1f"], ref: "14#Seaside_Cave", type: "story", loc: "Seaside Cave", title: "Seaside Cave: use the Colress MCHN on the odd boulder",
        text: "Surf south down Route 21 to the cave (you need Surf and Strength)." +
          "<ol><li>1F: go south over the ledges, jump the northern ledge, head east, go down the stairs to the water, Surf north, then go down to B1F.</li>" +
          "<li>B1F: push the boulder into the hole. On the big platform, push the boulders into place with Strength, then go northwest back to 1F.</li>" +
          "<li>1F: jump the lower ledge, climb the opposite stairs, and use the <b>Colress MCHN</b> on the boulder blocking the east exit. It's a <b>Crustle</b>, so battle it.</li></ol>" },
      { id: "p14-board", ref: "14#Route_21_(east)", type: "story", loc: "Route 21", title: "Board the Plasma Frigate with Hugh",
        text: "Marlon lowers the gangplank. Beat a Grunt at the top, then follow Hugh in through the North Entrance. Inside, the two of you tag-battle two Grunts." },
      { id: "p14-barrier", ref: "14#{B1FB2|B1FW2}", type: "story", loc: "Route 21", title: "Shut off the electric barrier on B1F",
        text: "{<b>Black 2: four switches.</b> The warp panels in the six rooms around the stairwell take you back to switches in the North Entrance. Find and flip all four, then take the teleporter.|<b>White 2: password.</b> Get the <b>Plasma Card</b> from the female Grunt in the dining hall (west/southwest room). Talk to Grunts to collect the 5 clues; the password is different every playthrough. Enter it at the barrier, then take the teleporter.}<br>The bed in the {northeast|east} room heals your party." },
      { id: "p14-command", ref: "14#Command_Center", type: "boss", loc: "Route 21", title: "Command Center: Zinzolin + Grunt (tag battle with Hugh)",
        text: "Zinzolin shows off Kyurem, which is powering the ship.",
        boss: { who: "Zinzolin & Grunt (multi)", team: [["Cryogonal", 48, "Ice"], ["Cryogonal", 48, "Ice"], ["Weavile", 50, "Dark/Ice"], ["Liepard", 45, "Dark"], ["Watchog", 45, "Normal"], ["Scolipede", 45, "Bug/Poison"]],
          use: "Fighting covers nearly everything. Use Psychic, Fire, or Flying on Scolipede.", reward: "" } },
      { id: "p14-chasm", ref: "14#Outer_Cave", mapPin: [35.0, 15.9], mapLabel: "Entrance from Route 22", type: "story", loc: "Giant Chasm", map: "giant-chasm", title: "Fly to Humilau, take the Route 22 shortcut, enter the Giant Chasm",
        text: "Go south from the entrance. Hugh and a former Plasma spy drive off the Grunts. Move the boulder with Strength, then go southwest and jump the ledge into the <b>Crater Forest</b>." },
      { id: "p14-rood", ref: "14#Crater_Forest", map: "giant-chasm", mapPin: [56.7, 55.6], mapLabel: "Crater Forest", type: "boss", loc: "Giant Chasm", title: "Crater Forest: tag battle with Hugh",
        text: "Rood's old Plasma group is arguing with the new one. You and Hugh battle the Grunts. Afterward Rood gives you <b>3 Max Revives</b>. Climb the ice mound into the ship.",
        boss: null },
      { id: "p14-frigate", ref: "14#Plasma_Frigate_2", type: "story", loc: "Giant Chasm", title: "Frigate, round 2: South Entrance → B2F",
        text: "Beat the two Grunts in the South Entrance, then take the teleporter. On B2F, Rood's spy explains the room." +
          "{<br><b>Black 2: password.</b> Get the Plasma Card from the female Grunt on the north side of the pipe maze, collect the 5 clues, and enter the password.|<br><b>White 2: switches.</b> Use the pipe switches to move through the maze. The warp panels on the floor below lead to the 4 red switches.}" },
      { id: "p14-zinzolin", ref: "14#Plasma_Frigate_2", type: "boss", loc: "Giant Chasm", title: "Zinzolin (last time) in front of Kyurem's cage",
        boss: { who: "Zinzolin", team: [["Cryogonal", 49, "Ice"], ["Cryogonal", 49, "Ice"], ["Weavile", 51, "Dark/Ice"]],
          use: "Same plan as before: Fire and Fighting.", reward: "" },
        after: "Then take the <b>right</b> warp tile to the Control Room." },
      { id: "p14-colress", ref: "14#Plasma_Frigate_2", type: "boss", loc: "Giant Chasm", title: "Control Room: Colress",
        boss: { who: "Colress", team: [["Magneton", 50, "Electric/Steel", "Eviolite"], ["Beheeyem", 50, "Psychic"], ["Metang", 50, "Steel/Psychic"], ["Magnezone", 50, "Electric/Steel"], ["Klinklang", 52, "Steel", "Air Balloon"]],
          use: "<b>Ground</b> (4× on the Magne line) and <b>Fire</b>. Klinklang's Air Balloon makes it immune to Ground until the balloon pops. Use Dark or Ghost on Beheeyem.", reward: "" },
        after: "Afterward, take the warp on the <b>west</b> side of Kyurem's cage." },
      { id: "p14-triad", ref: "14#Plasma_Frigate_2", type: "boss", loc: "Giant Chasm", title: "Ghetsis' quarters: Shadow Triad ×3",
        text: "Each Shadow only fights when you talk to it, so <b>heal between battles</b>. Afterward Hugh gets his sister's Pokémon back (it's a Liepard now).",
        boss: { who: "Shadow Triad (3 separate battles)", team: [["Pawniard", 49, "Dark/Steel"], ["Pawniard", 49, "Dark/Steel"], ["Absol / Banette / Accelgor", 51, "Dark / Ghost / Bug"]],
          use: "Fighting (4× on Pawniard). Each Shadow's last Pokémon is different: Absol, then Banette, then Accelgor. Fire handles Accelgor.", reward: "" } },
      { id: "p14-kyuremfight", ref: "14#Inner_Cave", map: "giant-chasm", mapPin: [87.9, 18.8], mapLabel: "Cave depths", type: "boss", loc: "Giant Chasm", title: "Inner Cave: {Black|White} Kyurem (you can't catch it, just win)",
        text: "Leave the ship and go into the cave to the north. Ghetsis fuses Kyurem with N's {Zekrom|Reshiram}. Signals from Ghetsis' cane block capture, so you have to KO it.",
        boss: { who: "{Black|White} Kyurem", team: [["Kyurem", 55, "Dragon/Ice"]],
          use: "Fighting, Rock, Steel, Dragon.", reward: "" },
        callout: "Don't worry, you catch the normal <b>Kyurem</b> here after the Hall of Fame." },
      { id: "p14-ghetsis", ref: "14#Inner_Cave", type: "boss", loc: "Giant Chasm", title: "Ghetsis",
        boss: { who: "Ghetsis", team: [["Cofagrigus", 50, "Ghost", "Leftovers"], ["Seismitoad", 50, "Water/Ground"], ["Eelektross", 50, "Electric"], ["Drapion", 50, "Poison/Dark"], ["Toxicroak", 50, "Poison/Fighting"], ["Hydreigon", 52, "Dark/Dragon", "Life Orb"]],
          use: "Cofagrigus: Ghost or Dark. Seismitoad: <b>Grass (4×)</b>. Eelektross has no weaknesses (Levitate), so just hit hard. Drapion: Ground. Toxicroak: <b>Psychic (4×)</b>, Flying, or Ground. Hydreigon: <b>Fighting, Ice, Dragon, or Bug</b>.", reward: "" },
        after: "Afterward, Hugh tells you that Route 23 is through the <b>west</b> side of the outer cave." },
    ],
  },

  /* ============================ PART 15 ============================ */
  {
    id: "p15", refs: [15], part: "Part 15", title: "Victory Road & the Pokémon League",
    areas: "Route 23 · Victory Road · Pokémon League",
    steps: [
      { id: "p15-heal", ref: "15#East_side", type: "heal", loc: "Route 23", title: "The Ace Trainer in the house north of the cave exit heals you",
        text: "Handy right after Ghetsis." },
      { id: "p15-route23", ref: "15#West_side", type: "story", loc: "Route 23", title: "Route 23: head north to Victory Road",
        text: "Follow the river valley north to the big stairway, then head <b>west</b> through the forest. Chop trees and push boulders to get through. Then go north to Victory Road.",
        callout: "<b>Azelf</b> shows up post-game on the platform near the Strength puzzle in this west forest." },
      { id: "p15-n", ref: "15#Entrance", mapPin: [32.5, 18.0], mapLabel: "Entrance & Pokémon Center", type: "story", loc: "Victory Road", map: "victory-road", title: "N gives you HM05 Waterfall at the entrance",
        text: "Pass the Badge Check Gate. There's a Pokémon Center to the northeast. Bring Pokémon that know <b>Cut, Surf, Strength, Waterfall, and Flash</b>." },
      { id: "p15-vr", ref: "15#{Pokémon_Black_2|Pokémon_White_2}", mapPin: [76.6, 64.3], mapLabel: "Exit to the Pokémon League", type: "story", loc: "Victory Road", map: "victory-road", title: "Climb Victory Road (follow the map)",
        text: "The route is different in each version, so use the map. Both versions go: Cave 1F → River Valley → Cave 2F → Mountainside → Cave 2F Back (use <b>Flash</b>) → Mountainside → Cave 3F → outside → north path." +
          "<br>A <b>Zoroark</b> guards a cave entrance on the east side. Leave it alone for now; it leads to N's Castle post-game." },
      { id: "p15-hugh", ref: "15#Northern_path", type: "boss", loc: "Victory Road", title: "Rival battle: Hugh in the final tunnel",
        text: "Past Veterans Portia and Sterling. He gives you <b>TM24 Thunderbolt</b> afterward.",
        boss: { who: "Rival Hugh", rival: true, team: [["Unfezant", 55, "Normal/Flying", "Scope Lens"], ["$monkey", 55], ["Bouffalant", 55, "Normal"], ["$ace", 57]],
          use: "Electric, Rock, or Ice for Unfezant. Fighting for Bouffalant. For the other two, use whatever beats his starter.", reward: "TM24 Thunderbolt" } },
      { id: "p15-prep", ref: "15#Pokémon_League", type: "prep", loc: "Pokémon League", title: "League prep: aim for the 60s and stock Full Restores and Revives",
        text: "The Elite Four can be fought in any order. You warp back to the plaza after each one." },
      { id: "p15-shauntal", ref: "15#Left_room:_Shauntal", type: "boss", loc: "Pokémon League", title: "Elite Four: Shauntal (left)",
        boss: { who: "Shauntal", team: [["Cofagrigus", 56, "Ghost"], ["Drifblim", 56, "Ghost/Flying"], ["Golurk", 56, "Ground/Ghost"], ["Chandelure", 58, "Ghost/Fire", "Sitrus Berry"]],
          use: "Ghost and Dark. Water also hits Golurk and Chandelure.", reward: "" } },
      { id: "p15-grimsley", ref: "15#Center-left_room:_Grimsley", type: "boss", loc: "Pokémon League", title: "Elite Four: Grimsley (center-left)",
        boss: { who: "Grimsley", team: [["Liepard", 56, "Dark"], ["Scrafty", 56, "Dark/Fighting"], ["Krookodile", 56, "Ground/Dark"], ["Bisharp", 58, "Dark/Steel", "Sitrus Berry"]],
          use: "<b>Fighting</b> works on everything (4× on Bisharp). Use Flying on Scrafty, and Water, Grass, or Ice on Krookodile.", reward: "" } },
      { id: "p15-caitlin", ref: "15#Center-right_room:_Caitlin", type: "boss", loc: "Pokémon League", title: "Elite Four: Caitlin (center-right)",
        boss: { who: "Caitlin", team: [["Musharna", 56, "Psychic"], ["Sigilyph", 56, "Psychic/Flying"], ["Reuniclus", 56, "Psychic"], ["Gothitelle", 58, "Psychic", "Sitrus Berry"]],
          use: "Bug, Ghost, Dark.", reward: "" } },
      { id: "p15-marshal", ref: "15#Right_room:_Marshal", type: "boss", loc: "Pokémon League", title: "Elite Four: Marshal (right)",
        boss: { who: "Marshal", team: [["Throh", 56, "Fighting"], ["Sawk", 56, "Fighting"], ["Mienshao", 56, "Fighting"], ["Conkeldurr", 58, "Fighting", "Sitrus Berry"]],
          use: "Psychic and Flying. Sawk has Sturdy.", reward: "" } },
      { id: "p15-iris", ref: "15#The_Champion's_Temple", type: "boss", loc: "Pokémon League", title: "Champion Iris",
        text: "Check the plaque on the center statue to go down, then climb to the Champion's temple.",
        boss: { who: "Champion Iris", team: [["Hydreigon", 57, "Dark/Dragon"], ["Druddigon", 57, "Dragon", "Life Orb"], ["Aggron", 57, "Steel/Rock"], ["Archeops", 57, "Rock/Flying"], ["Lapras", 57, "Water/Ice"], ["Haxorus", 59, "Dragon", "Focus Sash"]],
          use: "Ice and Dragon for the dragons. Fighting or Ground for Aggron (4× each). Electric for Lapras and Archeops. Archeops loses half its power below 50% HP.", reward: "You're the Champion!" } },
    ],
  },

  /* ============================ POST-GAME ============================ */
  {
    id: "pg1", refs: [16, 17], part: "Post-game ①", title: "Lake Trio Trigger · Mesprit · The Regis",
    areas: "Aspertia City · Cave of Being · Celestial Tower · Clay Tunnel · Underground Ruins · Twist Mountain",
    postgame: true,
    intro: "This order keeps backtracking to a minimum. You wake up in Aspertia. Cedric Juniper upgrades your Pokédex to the National Dex, and the post-game opens up.",
    steps: [
      { id: "pg-being", ref: "16#Cave_of_Being", mapPin: [49.5, 72.5], mapLabel: "Juniper, center of the cave", type: "key", loc: "Cave of Being", map: "cave-of-being", title: "Cave of Being (Route 20): trigger the Lake Trio",
        text: "Climb the <b>waterfall</b> on the south side of Route 20 (HM05 from N) and go inside. Juniper is there, and <b>Uxie, Mesprit, and Azelf</b> appear and scatter across Unova.",
        callout: "To find each one, stand on its exact spot and it reveals itself. All three are Lv65." },
      { id: "pg-mesprit", ref: "16#Cave_of_Being", mapPin: [73.8, 72.0], mapLabel: "Foot of the bell platform", type: "legend", legend: "mesprit", loc: "Celestial Tower", map: "celestial-tower", title: "Mesprit: Celestial Tower rooftop (Lv65)",
        text: "Fly to Mistralton, go up Route 7, and climb to the roof. Stand at the <b>foot of the bell platform</b>.",
        tactic: "Bug, Ghost, Dark. It's bulky, so use status and Timer Balls." },
      { id: "pg-clay", ref: "17#Clay_Tunnel", mapPin: [93.1, 43.2], mapLabel: "Door to the Underground Ruins", type: "story", loc: "Clay Tunnel", map: "clay-tunnel", title: "Clay Tunnel (north of Driftveil): ride the mine carts to the ruins",
        text: "You need Strength and Surf. Bring <b>Dusk Balls</b>.<ol><li>Southern Cave: go east from Hiker Teppei and ride the mine cart.</li>" +
          "<li>Northern Cave: go east and take the next cart.</li><li>Southern Cave: push the boulder and talk to the Worker to ride again.</li>" +
          "<li>Eastern Cave: Worker → ride.</li><li>Northern Cave: Surf north and go through the doorway.</li><li>Eastern Cave: push the boulder and take the cart.</li>" +
          "<li>Northern Cave: go north and take the east doorway into the <b>Underground Ruins</b>.</li></ol>" },
      { id: "pg-regirock", ref: "17#Underground_Ruins", mapPin: [16.9, 17.3], mapLabel: "Regirock", type: "legend", legend: "regirock", loc: "Clay Tunnel", map: "underground-ruins", title: "Regirock: Underground Ruins (Lv65)",
        text: "Stand on the <b>center of the eye pattern</b> in the first chamber. Take <b>6 steps south, then 9 steps east</b>, and press A on the ground to find a hidden switch. The back room becomes the Rock Peak Chamber, and Regirock is at the far end.",
        tactic: "Water, Grass, Fighting, Ground, Steel. Dusk Balls work well here." },
      { id: "pg-registeel", ref: "17#Underground_Ruins", mapPin: [81.1, 17.0], mapLabel: "Registeel", type: "legend", legend: "registeel", loc: "Clay Tunnel", map: "underground-ruins", title: "Registeel: Iron Chamber (Lv65){| · needs the Iron Key from Black 2}",
        text: "{Catching Regirock unlocks the <b>Iron Key</b>. Save and quit, then on the title screen open <b>Unova Link → Key System</b> and turn the key on. Come back to the ruins and the chamber is now the Iron Chamber.|White 2 can't unlock the <b>Iron Key</b> itself. A <b>Black 2</b> game that has caught Regirock has it: send it to this game over <b>Unova Link → Key System</b>, then turn it on there. Come back to the ruins and the chamber is now the Iron Chamber.}",
        tactic: "Fire or Fighting first, then Ice or Grass to whittle it down.",
        callout: "{Native to Black 2.|<b>Black 2 only:</b> needs the Iron Key from a Black 2 game (or trade for Registeel).} Regigigas needs <b>all three</b> Regis." },
      { id: "pg-regice", ref: "17#Underground_Ruins", mapPin: [49.8, 17.4], mapLabel: "Regice", type: "legend", legend: "regice", loc: "Clay Tunnel", map: "underground-ruins", title: "Regice: Iceberg Chamber (Lv65){ · needs the Iceberg Key from White 2|}",
        text: "{Black 2 can't unlock the <b>Iceberg Key</b> itself. A <b>White 2</b> game that has caught Regirock has it: send it to this game over <b>Unova Link → Key System</b>, then turn it on there. Come back to the ruins and the chamber is now the Iceberg Chamber.|Catching Regirock unlocks the <b>Iceberg Key</b>. Save and quit, then on the title screen open <b>Unova Link → Key System</b> and turn the key on. Come back to the ruins and the chamber is now the Iceberg Chamber.}",
        tactic: "Fire or Fighting first, then weaker neutral moves to whittle it down.",
        callout: "{<b>White 2 only:</b> needs the Iceberg Key from a White 2 game (or trade for Regice).|Native to White 2.} Regigigas needs <b>all three</b> Regis." },
      { id: "pg-regigigas", ref: "17#Twist_Mountain", mapPin: [36.1, 82.0], mapLabel: "Regigigas", type: "legend", legend: "regigigas", loc: "Twist Mountain", map: "twist-mountain", title: "Regigigas: Twist Mountain hidden chamber (Lv68)",
        text: "Exit the ruins west, push the boulder, and go north into <b>Twist Mountain B1F</b>. North of the icy rock, move the boulders: <b>west one right, middle one down, east one left</b>. With <b>Regirock, Regice, and Registeel in your party</b>, check the \"statue\" and it wakes up.",
        tactic: "Slow Start halves its Attack and Speed for the first 5 turns, so catch it then. Fighting does the most damage. Use Dusk Balls." },
    ],
  },
  {
    id: "pg2", refs: [19], part: "Post-game ②", title: "Azelf · N's Castle · Zekrom/Reshiram · Kyurem",
    areas: "Route 23 · Victory Road · N's Castle · Dragonspiral Tower · Giant Chasm",
    postgame: true,
    steps: [
      { id: "pg-azelf", ref: "16#Cave_of_Being", type: "legend", legend: "azelf", loc: "Route 23", title: "Azelf: Route 23 west forest (Lv65)",
        text: "Fly to the Pokémon League and walk down to Route 23. In the <b>west forest</b>, stand on the <b>platform near the Strength puzzle</b>.",
        tactic: "Bug, Ghost, Dark. It's fast and hits hard, so use a Quick Ball on turn 1 or put it to sleep." },
      { id: "pg-zoroark", ref: "19#Victory_Road", mapPin: [84.4, 84.1], mapLabel: "N's Castle entrance", type: "story", loc: "Victory Road", map: "victory-road", title: "Victory Road: follow the Zoroark to N's Castle",
        text: "Go down the stairway south of the two Veterans and find the <b>Zoroark</b> from earlier. It leads you through the cave it was guarding and up a tall stairway to N's Castle." },
      { id: "pg-n", ref: "19#N's_Castle", type: "boss", loc: "N's Castle", title: "N's Castle: battle N and his {Zekrom|Reshiram}",
        text: "Follow N through the castle: 1F → his old room → 2F west to the crack in the floor → throne room.",
        boss: { who: "N", team: [["{Zekrom|Reshiram}", 70, "{Dragon/Electric|Dragon/Fire}"]],
          use: "{Ground or Ice. Ground types are immune to its Electric moves.|Ground, Rock, or Dragon, and switch in a Rock type to tank its Fire moves.}", reward: "{Dark Stone|Light Stone}" } },
      { id: "pg-route-dst", ref: "19#Tubeline_Bridge", type: "story", loc: "Tubeline Bridge", title: "Travel to Dragonspiral Tower",
        text: "Fly to <b>Opelucid City</b> → west through Route 9 → <b>Tubeline Bridge</b> → Route 8 → <b>Icirrus City</b> → north to the tower." },
      { id: "pg-dst-climb", ref: "19#Dragonspiral_Tower", mapPin: [50.0, 30.0], mapLabel: "3F ramps", type: "story", loc: "Dragonspiral Tower", map: "dragonspiral-tower", title: "Climb Dragonspiral Tower to 7F",
        text: "1F is a straight path. 2F: use broken columns as bridges. 3F: one-way ramps, take the <b>southernmost</b> ramp west to the stairs. 4F and 6F are straight paths. 5F: circle the rings to the stairs on the left. 7F: walk up the narrow path." },
      { id: "pg-dragon", ref: "19#Dragonspiral_Tower", mapPin: [47.5, 84.6], mapLabel: "End of 6F: stairs up to 7F", type: "legend", legend: "{zekrom|reshiram}", loc: "Dragonspiral Tower", map: "dragonspiral-tower", title: "{Zekrom|Reshiram}: Dragonspiral Tower 7F (Lv70)",
        text: "The {Dark|Light} Stone wakes up into {Zekrom|Reshiram}. <b>Save first.</b>",
        tactic: "{Ground, Ice, or Dragon to bring it down, then Grass or Electric to whittle. If you KO it, beat the Elite Four again to respawn it.|Ground, Rock, or Dragon to bring it down, then Grass, Fire, or Electric to whittle. If you KO it, beat the Elite Four again to respawn it.}",
        callout: "Afterward, N tells you <b>Kyurem has returned</b> to the Giant Chasm." },
      { id: "pg-kyurem", ref: "19#Giant_Chasm", mapPin: [87.9, 18.8], mapLabel: "Kyurem, in the cave depths", type: "legend", legend: "kyurem", loc: "Giant Chasm", map: "giant-chasm", title: "Kyurem: Giant Chasm, back of the northeast cave (Lv70)",
        text: "Fly to Lacunosa and head into the Giant Chasm → Crater Forest → the cave to the <b>northeast</b> → back chamber. <b>Save before talking to it.</b>",
        tactic: "This is the hardest catch here, so use the <b>Master Ball</b>. Otherwise use Dusk and Timer Balls with Paralysis or Sleep. It's weak to Fighting, Rock, Steel, and Dragon.",
        callout: "Pick up the <b>DNA Splicers</b> afterward. They fuse Kyurem with {Zekrom|Reshiram} into {Black|White} Kyurem." },
    ],
  },
  {
    id: "pg3", refs: [18, 20, 21, 22], part: "Post-game ③", title: "Cresselia · Uxie · {Latios|Latias} · Heatran",
    areas: "Route 14 · Marvelous Bridge · Nacrene City · Dreamyard · Route 18 · Reversal Mountain",
    postgame: true,
    steps: [
      { id: "pg-route14", ref: "18#Route_14", type: "story", loc: "Route 14", title: "Undella Town → Route 14 → {Black City|White Forest} → Route 15",
        text: "Head south from Undella. Hugh also gives you <b>HM06 Dive</b> in Undella; you don't need it for any legendary." },
      { id: "pg-cresselia", ref: "18#Cresselia", type: "legend", legend: "cresselia", loc: "Marvelous Bridge", title: "Cresselia: Marvelous Bridge (Lv68)",
        text: "Walk under the <b>eastern archway</b>. The Lunar Wing starts to shine, you hold it up, and Cresselia swoops down. (You need the Lunar Wing from the Strange House.)",
        tactic: "Bug, Ghost, Dark. It's very bulky and doesn't hit back hard, so this one's easy with Timer Balls." },
      { id: "pg-skyarrow", ref: "20#Skyarrow_Bridge", type: "story", loc: "Skyarrow Bridge", title: "Fly to Castelia → Skyarrow Bridge → Pinwheel Forest → Nacrene City",
        text: "" },
      { id: "pg-uxie", ref: "20#Nacrene_Museum", type: "legend", legend: "uxie", loc: "Nacrene City", title: "Uxie: outside the Nacrene Museum (Lv65)",
        text: "Stand in the <b>center of the circular walkway</b> outside the Museum on the north side of town.",
        tactic: "Bug, Ghost, Dark. It's bulky, so bring Timer Balls." },
      { id: "pg-striaton", ref: "20#Hints_of_a_Legend", type: "story", loc: "Striaton City", title: "Route 3 → Striaton City",
        text: "Talk to people in the apartment building south of the Pokémon Center about a mysterious presence in the Dreamyard. You can skip this; the encounter is there either way." },
      { id: "pg-lati", ref: "20#The_Dreamyard", mapPin: [49.5, 36.5], mapLabel: "Easternmost walkway (approx.)", type: "legend", legend: "{latios|latias}", loc: "Dreamyard", map: "dreamyard", title: "{Latios|Latias}: Dreamyard (Lv68)",
        text: "{Latios|Latias} flies past several times as you go through. Cut the tree into the old factory, go west and up the stairs, then follow the walkway to its <b>easternmost point</b>. That's where it attacks.",
        tactic: "Dragon, Ice, Bug, Ghost, Dark, but it's frail to strong Dark moves, so don't KO it. A Dark type blocks its only attack. Psycho Shift sends status back at you." },
      { id: "pg-route18", ref: "21#Route_18", mapPin: [33.6, 44.3], mapLabel: "Magma Stone", type: "key", loc: "Route 18", map: "route-17-18-p2-lab", title: "Get the Magma Stone on Route 18",
        text: "Route 2 → Accumula Town → <b>Route 1</b> → Surf west through <b>Route 17</b> → <b>Route 18</b>. Climb the stairs, go down into the valley, then up the northeast stairway (Crasher Wake is there). Cross the next bridge to get the <b>Magma Stone</b>." },
      { id: "pg-heatran", ref: "22#Reversal_Mountain", mapPin: { b2: [66.6, 28.7], w2: [65.6, 73.5] }, mapLabel: "Heatran's chamber", type: "legend", legend: "heatran", loc: "Reversal Mountain", map: "reversal-mountain", title: "Heatran: Reversal Mountain B1F (Lv68)",
        text: "Fly to Lentimas Town and go into Reversal Mountain. Find <b>Doctor Derek</b> and take the stairway near him down to Heatran's chamber on B1F. <b>Save</b>, use the Magma Stone, then talk to Heatran.",
        tactic: "Paralyze it first. Hit it with neutral moves and keep a Water type in to take its Fire and Steel hits. Ground is 4×, so don't KO it by accident. Use Dusk Balls." },
      { id: "pg-done", ref: "22#Pokémon_League:_Round_2", type: "story", loc: "Pokémon League", title: "That's every legendary you can catch in your version.",
        text: "Optional extras: Elite Four rematches (Lv72–78), the Nature Preserve shiny Haxorus (Unova Dex completion → Permit), and more." },
    ],
  },
];

/* ---------------------------------------------------------------------------
   Game module registration — everything the shared renderer needs.
--------------------------------------------------------------------------- */
window.GAME = {
  id: "b2w2",
  gen: 5,                                   // picks the type chart and Pokémon typings for the Types panel
  title: "B2W2 Legendary Route",
  tagline: "Main story from Part 1 to every catchable legendary",
  // First entry = text before "|" in {a|b} placeholders, second = after.
  versions: [
    { id: "b2", label: "Black 2", mode: "dark",  accent: "#33c3f0", accent2: "#1b8fd1", ink: "#04121a" },
    { id: "w2", label: "White 2", mode: "light", accent: "#e8462f", accent2: "#c0321d", ink: "#ffffff" },
  ],
  sprites: "assets/sprites/gen5",           // {dex}.png static, {dex}.gif animated
  regionMaps: { b2: { drive: "1LH6LxC3gznFS2haUMOJIMULeRCqZ1tdY" }, w2: { drive: "18xBlX1_dxuQ-DhgMQsD06aQKfVt0uMNY" } }, // MewMaps Drive files
  regionName: "Unova",
  pins: PINS,
  maps: MAPS,
  starter: {
    label: "Starter",
    options: [["snivy", "Snivy"], ["tepig", "Tepig"], ["oshawott", "Oshawott"]],
    // Fills "$ace" / "$monkey" in rival teams: [name, types, held item]
    slots: {
      snivy:    { base: ["Tepig", "Fire"],      mid: ["Pignite", "Fire/Fighting", "Charcoal"], ace: ["Emboar", "Fire/Fighting", "Charcoal"],  monkey: ["Simipour", "Water", "Mystic Water"] },
      tepig:    { base: ["Oshawott", "Water"],  mid: ["Dewott", "Water", "Mystic Water"],      ace: ["Samurott", "Water", "Mystic Water"],    monkey: ["Simisage", "Grass", "Miracle Seed"] },
      oshawott: { base: ["Snivy", "Grass"],     mid: ["Servine", "Grass", "Miracle Seed"],     ace: ["Serperior", "Grass", "Miracle Seed"],   monkey: ["Simisear", "Fire", "Charcoal"] },
    },
  },
  legends: LEGENDS,
  notInGame: NOT_IN_GAME,
  catchKit: [
    "<b>Master Ball</b>: save it for Kyurem",
    "<b>Dusk Balls</b>: 3.5× in caves and at night",
    "<b>Timer Balls</b>: 4× after 10+ turns",
    "<b>Quick Ball</b>: throw it on turn 1",
    "Sleep or Paralysis user (Spore, Hypnosis, Thunder Wave)",
    "False Swipe user, so you never KO by accident",
    "<b>Save before every legendary</b>",
  ],
  postgameBanner: "🏆 Post-game: the legendary hunt. Everything below happens after you enter the Hall of Fame.",
  chapters: CHAPTERS,
  // Old step id → new one ({b2|w2} allowed), so saved check-offs carry over.
  renamedSteps: { "pg-regikey": "{pg-registeel|pg-regice}" },
  // Step/part links: ref "10#Celestial_Tower" → <base>10#Celestial_Tower ({b2|w2} allowed in the anchor)
  walkthrough: {
    label: "Bulbapedia",
    base: "https://bulbapedia.bulbagarden.net/wiki/Walkthrough:Pok%C3%A9mon_Black_2_and_White_2/Part_",
    partLabel: (n) => `Part ${n}`,
    sections: SECTIONS,
  },
  sources: [
    ["Bulbapedia B2W2 walkthrough", "https://bulbapedia.bulbagarden.net/wiki/Walkthrough:Pok%C3%A9mon_Black_2_and_White_2"],
    ["MewMaps", "https://www.mewmaps.org/black-2-white-2"],
  ],
};
})();
