/* =========================================================================
   Pokémon X / Y — Streamlined Route (story → every catchable legendary)
   Story content condensed from Bulbapedia's X and Y walkthrough (Parts 1–17).
   Dungeon maps from mewmaps.org, town/route maps from Bulbapedia's archive.
   Personal reference only.

   Step types: story · boss · legend · key · prep · heal · tip (tip = hidden unless "Show extras").
   Version text uses {x|y}. Starter-dependent names use ${slot} (see starter.slots), and a
   step's `legend: "$bird"` picks the legendary named by that slot.
   ========================================================================= */
(() => {
"use strict";

// Region-map pin coordinates (percent of the MewMaps Kalos map's width/height), checked on the image.
const PINS = {
  "Vaniville Town": [75.1, 89.6],
  "Route 1": [74.9, 86.0],
  "Aquacorde Town": [74.9, 82.0],
  "Route 2": [75.1, 73.7],
  "Santalune Forest": [74.5, 65.8],
  "Route 3": [71.5, 61.6],
  "Route 20": [81.4, 57.8],
  "Pokémon Village": [83.2, 60.7],
  "Santalune City": [65.5, 56.5],
  "Route 4": [60.3, 52.4],
  "Route 22": [71.5, 52.8],
  "Victory Road": [74.7, 47.0],
  "Route 21": [80.3, 47.8],
  "Anistar City": [85.7, 31.2],
  "Terminus Cave": [91.0, 35.2],
  "Route 18": [88.2, 37.0],
  "Couriway Town": [91.4, 40.1],
  "Route 19": [91.6, 43.7],
  "Snowbelle City": [85.7, 47.2],
  "Route 17": [78.5, 30.7],
  "Dendemille Town": [73.6, 25.4],
  "Frost Cavern": [75.3, 20.9],
  "Poké Ball Factory": [53.1, 7.6],
  "Laverre City": [54.6, 16.7],
  "Route 14": [54.6, 26.4],
  "Route 15": [65.5, 22.7],
  "Lost Hotel": [70.2, 24.4],
  "Route 16": [67.8, 36.1],
  "Sea Spirit's Den": [10.2, 30.8],
  "Azure Bay": [14.7, 32.0],
  "Coumarine City": [33.0, 31.1],
  "Route 12": [21.0, 39.9],
  "Route 13": [41.0, 36.8],
  "Kalos Power Plant": [39.6, 42.0],
  "Shalour City": [9.0, 43.5],
  "Parfum Palace": [33.0, 52.6],
  "Reflection Cave": [19.6, 54.8],
  "Route 11": [14.0, 59.8],
  "Geosenge Town": [10.0, 61.4],
  "Route 10": [14.0, 65.4],
  "Cyllage City": [25.8, 74.7],
  "Route 8": [31.3, 76.7],
  "Ambrette Town": [32.6, 80.6],
  "Route 9": [38.3, 78.0],
  "Connecting Cave": [29.5, 71.4],
  "Route 7": [36.9, 65.4],
  "Route 6": [36.3, 59.8],
  "Camphrier Town": [43.1, 60.1],
  "Route 5": [45.6, 52.2],
  "Glittering Cave": [39.7, 75.6],
  "Kiloude City": [89.5, 95.1],
  "Lumiose City": [53.2, 41.0],
  "Pokémon League": [73.6, 45.0],
  // places inside a city, or reached from one, use that spot
  "Lumiose Gym": [53.2, 41.0],
  "Lysandre Café": [53.2, 41.0],
  "Lysandre Labs": [53.2, 41.0],
  "Team Flare Secret HQ": [10.0, 61.4],
  "Unknown Dungeon": [83.2, 60.7],
};

// Location maps. MewMaps (Google Drive) for dungeons and Lumiose; Bulbapedia's archive for towns and routes.
// `locs`: other place names this map covers (steps there get its button; the names link to it in text).
const MAPS = {
  "lumiose-city": { name: "Lumiose City", drive: "1XrY79KzamE1_LwaxQBgsWOjGP6UiKK7m", locs: ["Lysandre Café", "Lysandre Labs", "Prism Tower", "Lumiose Station"] },
  "connecting-cave": { name: "Connecting Cave", drive: "1XVSl0_k9rcmTDU5eEEGLBjoqXPkkvGYH" },
  "glittering-cave": { name: "Glittering Cave", drive: "17F5FpgUp_e69bBG6ZmO9sTfW6MsshiB3" },
  "reflection-cave": { name: "Reflection Cave", drive: "1XMryeWQN8RwkMJ6uRBf16EXQdF2KsZur" },
  "power-plant": { name: "Kalos Power Plant", drive: "1QIePx44V0CBNlw4upHN9nhkkyojjaUM1", locs: ["Power Plant"] },
  "poke-ball-factory": { name: "Poké Ball Factory", drive: "1ZhpvZEqlebr7F5Ehl6K5wzQ9YrwjR709" },
  "lost-hotel": { name: "Lost Hotel", drive: "1bikXFP7Ne6R8tpRt6xR5GhaL42sA4G8A" },
  "frost-cavern": { name: "Frost Cavern", drive: "1-l7rr7zTfDERs-m33iM8Htha_0icM6gX" },
  "terminus-cave": { name: "Terminus Cave", drive: "1ukRLLTq8yXzbA3jkELAcIbxnWkqwqTwB" },
  "victory-road": { name: "Victory Road", drive: "1wWIa5JCfiKQaaFC9g2ogGtoFHE-kDbFP", locs: ["Pokémon League"] },

  "vaniville-town": { name: "Vaniville Town", bulba: "Vaniville Town XY.png" },
  "route-1": { name: "Route 1", bulba: "Kalos Route 1 XY.png" },
  "aquacorde-town": { name: "Aquacorde Town", bulba: "Aquacorde Town XY.png" },
  "route-2": { name: "Route 2", bulba: "Kalos Route 2 XY.png" },
  "santalune-forest": { name: "Santalune Forest", bulba: "Santalune Forest XY.png" },
  "route-3": { name: "Route 3", bulba: "Kalos Route 3 XY.png" },
  "santalune-city": { name: "Santalune City", bulba: "Santalune City XY.png", locs: ["Santalune Gym"] },
  "route-4": { name: "Route 4", bulba: "Kalos Route 4 XY.png" },
  "route-5": { name: "Route 5", bulba: "Kalos Route 5 XY.png" },
  "camphrier-town": { name: "Camphrier Town", bulba: "Camphrier Town XY.png", locs: ["Shabboneau Castle"] },
  "route-6": { name: "Route 6", bulba: "Kalos Route 6 XY.png" },
  "route-7": { name: "Route 7", bulba: "Kalos Route 7 XY.png", locs: ["Battle Chateau"] },
  "parfum-palace": { name: "Parfum Palace", bulba: "Parfum Palace XY.png" },
  "parfum-gardens": { name: "Parfum Palace gardens", bulba: "Parfum Palace Courtyard XY.png" },
  "route-8": { name: "Route 8", bulba: "Kalos Route 8 XY.png" },
  "ambrette-town": { name: "Ambrette Town", bulba: "Ambrette Town XY.png" },
  "route-9": { name: "Route 9", bulba: "Kalos Route 9 XY.png" },
  "cyllage-city": { name: "Cyllage City", bulba: "Cyllage City XY.png", locs: ["Cyllage Gym"] },
  "route-10": { name: "Route 10", bulba: "Kalos Route 10 XY.png" },
  "geosenge-town": { name: "Geosenge Town", bulba: "Geosenge Town XY.png" },
  "route-11": { name: "Route 11", bulba: "Kalos Route 11 XY.png" },
  "shalour-city": { name: "Shalour City", bulba: "Shalour City XY.png", locs: ["Shalour Gym", "Tower of Mastery"] },
  "route-12": { name: "Route 12", bulba: "Kalos Route 12 XY.png" },
  "azure-bay": { name: "Azure Bay", bulba: "Azure Bay XY.png" },
  "coumarine-city": { name: "Coumarine City", bulba: "Coumarine City XY.png", locs: ["Coumarine Gym"] },
  "route-13": { name: "Route 13", bulba: "Kalos Route 13 XY.png" },
  "lumiose-gym": { name: "Lumiose Gym", bulba: "Lumiose Gym 2F 3F 4F 5F XY.png" },
  "route-14": { name: "Route 14", bulba: "Kalos Route 14 XY.png" },
  "laverre-city": { name: "Laverre City", bulba: "Laverre City XY.png", locs: ["Laverre Gym"] },
  "route-15": { name: "Route 15", bulba: "Kalos Route 15 XY.png" },
  "dendemille-town": { name: "Dendemille Town", bulba: "Dendemille Town XY.png" },
  "route-17": { name: "Route 17", bulba: "Kalos Route 17 XY.png" },
  "anistar-city": { name: "Anistar City", bulba: "Anistar City XY.png", locs: ["Anistar Gym"] },
  "team-flare-hq": { name: "Team Flare Secret HQ", bulba: "Team Flare Secret HQ XY.png" },
  "route-18": { name: "Route 18", bulba: "Kalos Route 18 XY.png" },
  "couriway-town": { name: "Couriway Town", bulba: "Couriway Town XY.png" },
  "route-19": { name: "Route 19", bulba: "Kalos Route 19 XY.png" },
  "snowbelle-city": { name: "Snowbelle City", bulba: "Snowbelle City XY.png", locs: ["Snowbelle Gym"] },
  "route-20": { name: "Route 20", bulba: "Kalos Route 20 XY.png", locs: ["Winding Woods"] },
  "pokemon-village": { name: "Pokémon Village", bulba: "Pokémon Village XY.png", locs: ["Unknown Dungeon"] },
  "route-21": { name: "Route 21", bulba: "Kalos Route 21 XY.png" },
  "kiloude-city": { name: "Kiloude City", bulba: "Kiloude City XY.png" },
  "sea-spirits-den": { name: "Sea Spirit's Den", bulba: "Sea Spirit's Den interior XY.png" },
};

/* ---------------------------------------------------------------------------
   Legendaries catchable in-game (no events).
   ver: "both" | "x" | "y". starter: only in a save that picked that starter.
--------------------------------------------------------------------------- */
const LEGENDS = [
  { id: "xerneas", name: "Xerneas", dex: 716, lvl: 50, types: ["Fairy"], ver: "x", phase: "story",
    where: "Team Flare Secret HQ", step: "p11-legend",
    hit: "Poison, Steel", avoid: "Dragon moves (no effect)",
    note: "If it faints or you run, it reappears right away. You must catch it to continue." },
  { id: "yveltal", name: "Yveltal", dex: 717, lvl: 50, types: ["Dark", "Flying"], ver: "y", phase: "story",
    where: "Team Flare Secret HQ", step: "p11-legend",
    hit: "Electric, Ice, Rock, Fairy", avoid: "Psychic and Ground moves (no effect)",
    note: "If it faints or you run, it reappears right away. You must catch it to continue." },
  { id: "articuno", name: "Articuno", dex: 144, lvl: 70, types: ["Ice", "Flying"], ver: "both", starter: "chespin", phase: "post",
    where: "Roams Kalos, then Sea Spirit's Den", step: "pg-bird", requires: "Chespin as your starter",
    hit: "Rock (4×), Fire, Electric, Steel", avoid: "",
    note: "If it faints, it comes back after you enter the Hall of Fame again. If you run, it roams again." },
  { id: "zapdos", name: "Zapdos", dex: 145, lvl: 70, types: ["Electric", "Flying"], ver: "both", starter: "fennekin", phase: "post",
    where: "Roams Kalos, then Sea Spirit's Den", step: "pg-bird", requires: "Fennekin as your starter",
    hit: "Rock, Ice", avoid: "Ground moves (no effect)",
    note: "If it faints, it comes back after you enter the Hall of Fame again. If you run, it roams again." },
  { id: "moltres", name: "Moltres", dex: 146, lvl: 70, types: ["Fire", "Flying"], ver: "both", starter: "froakie", phase: "post",
    where: "Roams Kalos, then Sea Spirit's Den", step: "pg-bird", requires: "Froakie as your starter",
    hit: "Rock (4×), Water, Electric", avoid: "Ground moves (no effect)",
    note: "If it faints, it comes back after you enter the Hall of Fame again. If you run, it roams again." },
  { id: "mewtwo", name: "Mewtwo", dex: 150, lvl: 70, types: ["Psychic"], ver: "both", phase: "post",
    where: "Unknown Dungeon (Pokémon Village)", step: "pg-mewtwo", requires: "Become the Champion",
    hit: "Bug, Ghost, Dark", avoid: "",
    note: "Heals with Recover. If it faints, it comes back after you enter the Hall of Fame again." },
  { id: "zygarde", name: "Zygarde", dex: 718, lvl: 70, types: ["Dragon", "Ground"], ver: "both", phase: "post",
    where: "Terminus Cave (deepest chamber)", step: "pg-zygarde", requires: "Become the Champion",
    hit: "Ice (4×), Dragon, Fairy", avoid: "Electric moves (no effect)",
    note: "Camouflage makes it a pure Rock type. If it faints or you run, it comes back after you enter the Hall of Fame again." },
];

const NOT_IN_GAME = [
  ["The other two Kanto birds", "only one of Articuno, Zapdos and Moltres appears, picked by your starter. Trade for the others"],
  ["{Yveltal|Xerneas}", "{Y|X} only. Trade for it"],
];

// Bulbapedia walkthrough sections per part: [label, anchor] (powers the "More on Bulbapedia" lists)
const SECTIONS = {
  1: [["Intro", "Intro"], ["Vaniville Town", "Vaniville_Town"], ["Home", "Home"], ["Route 1", "Route_1"], ["Aquacorde Town", "Aquacorde_Town"], ["The Meeting Place", "The_Meeting_Place"], ["Vaniville Town", "Vaniville_Town_2"], ["Home", "Home_2"], ["Aquacorde Town", "Aquacorde_Town_2"]],
  2: [["Route 2", "Route_2"], ["Catching a Pokémon", "Catching_a_Pokémon"], ["Santalune Forest", "Santalune_Forest"], ["The Group Returns", "The_Group_Returns"], ["Route 3", "Route_3"], ["The Group Departs", "The_Group_Departs"], ["Santalune City", "Santalune_City"], ["Pokémon Center", "Pokémon_Center"], ["Santalune Boutique", "Santalune_Boutique"], ["Time for a Trade", "Time_for_a_Trade"], ["Trainers' School", "Trainers'_School"], ["Rinka the Roller Skater", "Rinka_the_Roller_Skater"], ["Santalune Gym", "Santalune_Gym"], ["The Journalist", "The_Journalist"], ["Route 4", "Route_4"], ["Sina and Dexio", "Sina_and_Dexio"]],
  3: [["Lumiose City", "Lumiose_City"], ["South Boulevard", "South_Boulevard"], ["Vernal Avenue", "Vernal_Avenue"], ["Gate to Route 5", "Gate_to_Route_5"], ["Route 5", "Route_5"], ["Meet Korrina", "Meet_Korrina"], ["Tierno and Trevor", "Tierno_and_Trevor"], ["Berry Tree", "Berry_Tree"], ["Traffic Cones and a TM", "Traffic_Cones_and_a_TM"], ["Camphrier Town", "Camphrier_Town"], ["Meet Cassius", "Meet_Cassius"], ["Name Rater", "Name_Rater"], ["Hotel Camphrier", "Hotel_Camphrier"], ["Tasty Treats", "Tasty_Treats"], ["Shabboneau Castle", "Shabboneau_Castle"]],
  4: [["Route 7 (east)", "Route_7_(east)"], ["Berry Fields", "Berry_Fields"], ["The Caretaker and the Crisis", "The_Caretaker_and_the_Crisis"], ["Route 6", "Route_6"], ["Parfum Palace", "Parfum_Palace"], ["Entrance", "Entrance"], ["Interior", "Interior"], ["Courtyard", "Courtyard"], ["Balcony", "Balcony"], ["Route 7 (west)", "Route_7_(west)"], ["Snorlax", "Snorlax"], ["Pokémon Day Care", "Pokémon_Day_Care"], ["Battle Chateau", "Battle_Chateau"], ["Multi Battle!", "Multi_Battle!"], ["Connecting Cave", "Connecting_Cave"]],
  5: [["Route 8 (upper)", "Route_8_(upper)"], ["Sina and Dexio", "Sina_and_Dexio"], ["Stepping Stones", "Stepping_Stones"], ["Try a Sky Battle", "Try_a_Sky_Battle"], ["Ambrette Town", "Ambrette_Town"], ["Meet up with Serena/Calem", "Meet_up_with_Serena/Calem"], ["A Smashing Good Time", "A_Smashing_Good_Time"], ["Trading Time", "Trading_Time"], ["Fossil Lab", "Fossil_Lab"], ["A Request", "A_Request"], ["Hotel Ambrette", "Hotel_Ambrette"], ["Route 9", "Route_9"], ["Ride with Rhyhorn", "Ride_with_Rhyhorn"], ["Glittering Cave", "Glittering_Cave"], ["1F", "1F"], ["B1F", "B1F"], ["Ambrette Town", "Ambrette_Town_2"], ["Fossil Lab", "Fossil_Lab_2"], ["Ambrette Aquarium", "Ambrette_Aquarium"], ["Route 8 (lower)", "Route_8_(lower)"], ["Treasure Hunting", "Treasure_Hunting"], ["Cyllage City", "Cyllage_City"], ["Time for a Trade", "Time_for_a_Trade"], ["Cycle Shop", "Cycle_Shop"], ["Poké-Massage", "Poké-Massage"], ["Pop Quiz", "Pop_Quiz"], ["Hotel Cyllage", "Hotel_Cyllage"], ["Collect an HM", "Collect_an_HM"], ["Cyllage Gym", "Cyllage_Gym"]],
  6: [["Route 10", "Route_10"], ["Team Flare", "Team_Flare"], ["Geosenge Town", "Geosenge_Town"], ["Hotel Marine Snow", "Hotel_Marine_Snow"], ["Team Flare, Again!", "Team_Flare,_Again!"], ["Battle Korrina", "Battle_Korrina"], ["Route 11", "Route_11"], ["Receive a Holo Clip", "Receive_a_Holo_Clip"], ["Reflection Cave", "Reflection_Cave"], ["1F", "1F"], ["B1F", "B1F"], ["B2F", "B2F"], ["B1F", "B1F_2"], ["1F", "1F_2"], ["Shalour City", "Shalour_City"], ["Mr. Bonding", "Mr._Bonding"], ["Rewards from the Residents", "Rewards_from_the_Residents"], ["Hit the Beach!", "Hit_the_Beach!"], ["Tower of Mastery", "Tower_of_Mastery"], ["Shalour Gym", "Shalour_Gym"], ["Tower of Mastery", "Tower_of_Mastery_2"], ["A Gift", "A_Gift"]],
  7: [["Route 12", "Route_12"], ["Adopt a Lapras", "Adopt_a_Lapras"], ["Baa de Mer Ranch", "Baa_de_Mer_Ranch"], ["Azure Bay", "Azure_Bay"], ["Southern isle", "Southern_isle"], ["Southwest isle", "Southwest_isle"], ["Coumarine City", "Coumarine_City"], ["Lower", "Lower"], ["Upper", "Upper"], ["Route 13", "Route_13"], ["Hidden Items", "Hidden_Items"], ["Kalos Power Plant", "Kalos_Power_Plant"], ["The Traveler", "The_Traveler"]],
  8: [["Lumiose City", "Lumiose_City"], ["North Boulevard", "North_Boulevard"], ["Centrico Plaza", "Centrico_Plaza"], ["Lysandre Café", "Lysandre_Café"], ["North Boulevard", "North_Boulevard_2"], ["Autumnal Avenue", "Autumnal_Avenue"], ["Rouge Alley", "Rouge_Alley"], ["Hibernal Avenue", "Hibernal_Avenue"], ["Jaune Alley", "Jaune_Alley"], ["Vert Alley", "Vert_Alley"], ["Estival Avenue", "Estival_Avenue"]],
  9: [["Route 14", "Route_14"], ["Rival Battle", "Rival_Battle"], ["Scary House", "Scary_House"], ["Laverre City", "Laverre_City"], ["Pokémon Center", "Pokémon_Center"], ["Tiny and Tall", "Tiny_and_Tall"], ["Pokémon Fan Club", "Pokémon_Fan_Club"], ["Battle-Combo Move Tutor", "Battle-Combo_Move_Tutor"], ["Laverre Gym", "Laverre_Gym"], ["Poké Ball Factory", "Poké_Ball_Factory"], ["Route 15", "Route_15"], ["Holo Clip", "Holo_Clip"], ["Lost Hotel", "Lost_Hotel"], ["Route 16", "Route_16"], ["The Fishing Shack", "The_Fishing_Shack"]],
  10: [["Dendemille Town", "Dendemille_Town"], ["Sycamore Appears", "Sycamore_Appears"], ["Pokémon Center", "Pokémon_Center"], ["Madam Reminder and Move Deleter", "Madam_Reminder_and_Move_Deleter"], ["Mountain Pokédex rating", "Mountain_Pokédex_rating"], ["Gigantic Gourgeist", "Gigantic_Gourgeist"], ["Frost Cavern", "Frost_Cavern"], ["Exterior", "Exterior"], ["Interior", "Interior"], ["Route 17", "Route_17"], ["Hitch a Ride", "Hitch_a_Ride"], ["Holo Clip", "Holo_Clip"], ["Anistar City", "Anistar_City"], ["A Gift", "A_Gift"], ["Memory Girl", "Memory_Girl"], ["Pokémon Center", "Pokémon_Center_2"], ["Hidden Power Checker", "Hidden_Power_Checker"], ["Learn the Story of the Legendary", "Learn_the_Story_of_the_Legendary"], ["Lend a Pokémon", "Lend_a_Pokémon"], ["Rival battle", "Rival_battle"], ["Anistar Gym", "Anistar_Gym"], ["Holo Clip", "Holo_Clip_2"]],
  11: [["Lumiose City", "Lumiose_City"], ["Lysandre Café", "Lysandre_Café"], ["Lysandre Labs", "Lysandre_Labs"], ["Geosenge Town", "Geosenge_Town"], ["Enter the HQ", "Enter_the_HQ"], ["Team Flare Secret HQ", "Team_Flare_Secret_HQ"], ["Aftermath", "Aftermath"], ["Anistar City", "Anistar_City"]],
  12: [["Route 18", "Route_18"], ["Inverse Battle house", "Inverse_Battle_house"], ["Terminus Cave", "Terminus_Cave"], ["Couriway Town", "Couriway_Town"], ["Meet up with Sycamore", "Meet_up_with_Sycamore"], ["Talk with the Townspeople", "Talk_with_the_Townspeople"], ["Couriway Hotel", "Couriway_Hotel"], ["Route 19", "Route_19"], ["Challenge Accepted", "Challenge_Accepted"]],
  13: [["Snowbelle City", "Snowbelle_City"], ["Pokémon Center", "Pokémon_Center"], ["Move Tutor", "Move_Tutor"], ["Time for a Trade", "Time_for_a_Trade"], ["Route 20", "Route_20"], ["Entrance", "Entrance"], ["Area 1", "Area_1"], ["Area 2", "Area_2"], ["Area 3", "Area_3"], ["Area 4", "Area_4"], ["Area 3", "Area_3_2"], ["Area 5", "Area_5"], ["Area 6", "Area_6"], ["Area 7", "Area_7"], ["Area 5", "Area_5_2"], ["Pokémon Village", "Pokémon_Village"], ["Meet Wulfric", "Meet_Wulfric"], ["Unknown Dungeon", "Unknown_Dungeon"], ["Snowbelle City", "Snowbelle_City_2"], ["Snowbelle Gym", "Snowbelle_Gym"]],
  14: [["Route 21", "Route_21"], ["Move Tutor", "Move_Tutor"], ["Strength puzzle", "Strength_puzzle"], ["Route 22", "Route_22"], ["Strength puzzle", "Strength_puzzle_2"], ["Chamber of Emptiness", "Chamber_of_Emptiness"], ["Victory Road", "Victory_Road"], ["Gate", "Gate"], ["Grove 1", "Grove_1"], ["Cave 1", "Cave_1"], ["Grove 2", "Grove_2"], ["Cave 2", "Cave_2"], ["Grove 2", "Grove_2_2"], ["Cave 2", "Cave_2_2"], ["Grove 3", "Grove_3"], ["Cave 3", "Cave_3"], ["Grove 4", "Grove_4"], ["Cave 4", "Cave_4"]],
  15: [["Pokémon League", "Pokémon_League"], ["Great Hall", "Great_Hall"], ["Blazing Chamber", "Blazing_Chamber"], ["Flood Chamber", "Flood_Chamber"], ["Ironworks Chamber", "Ironworks_Chamber"], ["Dragonmark Chamber", "Dragonmark_Chamber"], ["Radiant Chamber", "Radiant_Chamber"], ["Lumiose City", "Lumiose_City"]],
  16: [["Vaniville Town", "Vaniville_Town"], ["Homecoming", "Homecoming"], ["Time for a Trade", "Time_for_a_Trade"], ["Lumiose City", "Lumiose_City"], ["Sycamore Pokémon Lab", "Sycamore_Pokémon_Lab"], ["Café Soleil", "Café_Soleil"], ["Lumiose Station", "Lumiose_Station"], ["Kiloude City", "Kiloude_City"], ["Kiloude Station", "Kiloude_Station"], ["Pokémon Center", "Pokémon_Center"], ["Western house", "Western_house"], ["Northwest houses", "Northwest_houses"], ["Friend Safari", "Friend_Safari"], ["Battle Maison", "Battle_Maison"], ["The Northern Hill", "The_Northern_Hill"], ["Anistar City", "Anistar_City"], ["Lumiose City", "Lumiose_City_2"], ["Looker Bureau", "Looker_Bureau"]],
  17: [["Azure Bay", "Azure_Bay"], ["Sea Spirit's Den", "Sea_Spirit's_Den"], ["Pokémon Village", "Pokémon_Village"], ["Unknown Dungeon", "Unknown_Dungeon"], ["Route 18", "Route_18"], ["Terminus Cave", "Terminus_Cave"]],
};

// Rival (Serena/Calem) teams: Meowstic + Absol, then their starter line (the one strong against yours),
// plus an Eeveelution from Anistar on. Team order is as Bulbapedia lists it.
const RIVAL = "Serena/Calem";

const CHAPTERS = [
  /* ============================ PART 1 ============================ */
  {
    id: "p1", refs: [1], part: "Part 1", title: "A Starter & New Friends",
    areas: "Vaniville Town · Route 1 · Aquacorde Town",
    steps: [
      { id: "p1-home", ref: "1#Home", type: "story", loc: "Vaniville Town", title: "Wake up and meet your neighbors",
        text: "Change clothes at the mirror, then go outside. <b>Serena/Calem</b> and <b>Shauna</b> are waiting and invite you to Aquacorde Town, where everyone will get a Pokémon." },
      { id: "p1-route1", ref: "1#Route_1", type: "story", loc: "Route 1", title: "Walk north up Route 1",
        text: "A short path with no wild Pokémon." },
      { id: "p1-starter", ref: "1#The_Meeting_Place", type: "story", loc: "Aquacorde Town", title: "Pick Chespin, Fennekin or Froakie",
        text: "Your friends are at the outdoor table in the southwest. <b>Tierno</b> shows you the three Pokémon. Shauna then takes the one weak to yours, and Serena/Calem takes the last one. <b>Trevor</b> gives you the <b>Pokédex</b>, and Tierno gives you the <b>Prof's Letter</b>.",
        callout: "Set the <b>Starter</b> picker at the top of this page to match. Your rivals' teams and even which legendary bird you can catch depend on it." },
      { id: "p1-shauna", ref: "1#The_Meeting_Place", type: "boss", loc: "Aquacorde Town", title: "First battle: Shauna",
        boss: { who: "Pokémon Trainer Shauna", rival: true, team: [["$sbase", 5]],
          use: "Her starter is weak to yours. Just attack.", reward: "" } },
      { id: "p1-letter", ref: "1#Home_2", type: "story", loc: "Vaniville Town", title: "Deliver the Prof's Letter to Mom",
        text: "Go back home. Mom gives you the <b>Town Map</b> and a Potion. Then head north through Aquacorde Town, across the bridge, to Route 2." },
    ],
  },

  /* ============================ PART 2 ============================ */
  {
    id: "p2", refs: [2], part: "Part 2", title: "Santalune City & Viola",
    areas: "Route 2 · Santalune Forest · Route 3 · Santalune City · Santalune Gym · Route 4",
    badge: "Bug Badge (#1)",
    steps: [
      { id: "p2-catch", ref: "2#Catching_a_Pokémon", type: "story", loc: "Route 2", title: "Serena/Calem shows you how to catch Pokémon",
        text: "They give you <b>10 Poké Balls</b>, then go north." },
      { id: "p2-forest", ref: "2#The_Group_Returns", type: "story", loc: "Santalune Forest", title: "Cross Santalune Forest with Shauna",
        text: "Shauna joins you just inside and heals your team whenever you talk to her. Head northeast to the others, then west and north to the exit." },
      { id: "p2-route3", ref: "2#The_Group_Departs", type: "story", loc: "Route 3", title: "Route 3: the group splits up",
        text: "Serena/Calem gives everyone an Adventure Rules handbook. Continue north to Santalune City." },
      { id: "p2-trade", ref: "2#Time_for_a_Trade", type: "tip", loc: "Santalune City", title: "Trade a Bunnelby for Farfetch'd",
        text: "In the house west of the fountain. This Farfetch'd knows <b>Aerial Ace</b>, which is great against the Gym." },
      { id: "p2-rinka", ref: "2#Rinka_the_Roller_Skater", type: "story", loc: "Santalune City", title: "Beat Roller Skater Rinka for the Roller Skates",
        text: "She blocks the Gym door. The skates move with the Circle Pad; the D-Pad takes them off." },
      { id: "p2-gym", ref: "2#Santalune_Gym", type: "boss", loc: "Santalune City", title: "Santalune Gym: Viola",
        text: "Slide down the pole to the spider web. The dewdrops mark the path to the Leader.",
        boss: { who: "Gym Leader Viola", team: [["Surskit", 10, "Bug/Water"], ["Vivillon", 12, "Bug/Flying"]],
          use: "<b>Fire, Flying, Rock</b>. Both are also weak to Electric. Surskit's Water Sport weakens Fire, and Vivillon's Infestation traps you.", reward: "Bug Badge + TM83 Infestation" } },
      { id: "p2-alexa", ref: "2#The_Journalist", type: "story", loc: "Santalune City", title: "Alexa gives you the Exp. Share",
        text: "At the exit to Route 4. Viola's sister shares experience with your whole team (you can switch it off any time)." },
      { id: "p2-route4", ref: "2#Sina_and_Dexio", type: "story", loc: "Route 4", title: "Route 4: Sina and Dexio lead you to Lumiose City",
        text: "At the north end. In the gate, Dexio gives you TM27 Return." },
    ],
  },

  /* ============================ PART 3 ============================ */
  {
    id: "p3", refs: [3], part: "Part 3", title: "Professor Sycamore",
    areas: "Lumiose City (south) · Route 5 · Camphrier Town",
    steps: [
      { id: "p3-lab", ref: "3#South_Boulevard", type: "story", loc: "Lumiose City", title: "Sycamore Pokémon Lab, 3F",
        text: "A blackout keeps the city's north half closed for now. Sina takes you to the lab (heal at the Pokémon Center across the street first). On 2F a Scientist gives you 5 Luxury Balls." },
      { id: "p3-sycamore", ref: "3#South_Boulevard", type: "boss", loc: "Lumiose City", title: "Battle Professor Sycamore",
        boss: { who: "Pokémon Professor Sycamore", team: [["Bulbasaur", 10, "Grass/Poison"], ["Charmander", 10, "Fire"], ["Squirtle", 10, "Water"]],
          use: "Low levels but three different types. Hit each with what it's weak to.", reward: "A Kanto starter + its Mega Stone" },
        after: "Pick <b>Bulbasaur, Charmander or Squirtle</b>; he adds its Mega Stone. On the way out, the Scientist on 3F gives you <b>TM54 False Swipe</b>.",
        callout: "<b>False Swipe</b> never knocks out, so it's perfect for weakening legendaries. Teach it to someone you'll keep." },
      { id: "p3-cafe", ref: "3#South_Boulevard", type: "story", loc: "Lumiose City", title: "Café Soleil: meet Lysandre and Diantha",
        text: "Lysandre talks about making the world beautiful, and the movie star Diantha introduces herself. Then leave through the gate to Route 5 (southwest)." },
      { id: "p3-tierno", ref: "3#Tierno_and_Trevor", type: "boss", loc: "Route 5", title: "Route 5: battle Tierno",
        text: "Korrina rolls past with her Lucario near the start. Tierno and Trevor are southwest of the skate park.",
        boss: { who: "Pokémon Trainer Tierno", team: [["Corphish", 12, "Water"]],
          use: "Grass or Electric.", reward: "3 Honey (from Trevor)" } },
      { id: "p3-castle", ref: "3#Shabboneau_Castle", type: "story", loc: "Camphrier Town", title: "Shabboneau Castle: the caretaker is called to Route 7",
        text: "Shauna is inside asking about Mega Evolution. A man calls the caretaker away to a problem on Route 7, and Shauna suggests going too." },
    ],
  },

  /* ============================ PART 4 ============================ */
  {
    id: "p4", refs: [4], part: "Part 4", title: "Parfum Palace & Snorlax",
    areas: "Route 7 · Route 6 · Parfum Palace · Connecting Cave",
    steps: [
      { id: "p4-blocked", ref: "4#The_Caretaker_and_the_Crisis", type: "story", loc: "Route 7", title: "A Snorlax is asleep on the Route 7 bridge",
        text: "Only a Poké Flute can wake it, and the one the caretaker had is now at Parfum Palace, up Route 6 to the north." },
      { id: "p4-route6", ref: "4#Route_6", type: "story", loc: "Route 6", title: "Take the main road north to Parfum Palace", text: "" },
      { id: "p4-palace", ref: "4#Interior", type: "story", loc: "Parfum Palace", title: "Help the owner find his Furfrou",
        text: "Entry costs $1,000 (free if you have less). Shauna joins you. The owner has lost his Furfrou, so go out to the gardens.", map: "parfum-gardens" },
      { id: "p4-furfrou", ref: "4#Courtyard", type: "story", loc: "Parfum Palace", title: "Gardens: get HM01 Cut and corner Furfrou",
        text: "Cut is in the <b>southwest hedge</b>. Furfrou is in the northwest hedge and runs to a dead end. Have Shauna wait at the entrance, approach it from the west so it runs north, have her cover the east side, then loop around from the west to trap it.",
        map: "parfum-gardens" },
      { id: "p4-flute", ref: "4#Balcony", type: "key", loc: "Parfum Palace", title: "Balcony: fireworks, then the Poké Flute",
        text: "Go to the 2F center hall and talk to Shauna on the balcony. After the show the owner's butler hands over the <b>Poké Flute</b> (and TM17 Protect)." },
      { id: "p4-snorlax", ref: "4#Snorlax", type: "boss", loc: "Route 7", title: "Wake the Snorlax (you can catch it)",
        text: "Give the flute to the caretaker on the bridge. Heal first and bring Great Balls.",
        boss: { who: "Wild Snorlax", team: [["Snorlax", 15, "Normal", "Sitrus Berry"]],
          use: "<b>Fighting</b>. It raises its defenses with Defense Curl and Amnesia, so physical moves work better.", reward: "" } },
      { id: "p4-multi", ref: "4#Multi_Battle!", type: "boss", loc: "Route 7", title: "Multi Battle with Serena/Calem vs. Trevor & Tierno",
        text: "West of the Battle Chateau. Serena/Calem fights on your side.",
        boss: { who: "Trevor & Tierno", team: [["Pikachu", 14, "Electric"], ["Flabébé", 14, "Fairy"], ["Corphish", 16, "Water"]],
          use: "Knock out Tierno's Corphish (his only Pokémon) first, then focus Trevor.", reward: "" } },
      { id: "p4-cave", ref: "4#Connecting_Cave", type: "story", loc: "Connecting Cave", title: "Connecting Cave: take the southern tunnel to Route 8",
        text: "The north tunnel is blocked by boulders. The Scientist on the south side heals you." },
    ],
  },

  /* ============================ PART 5 ============================ */
  {
    id: "p5", refs: [5], part: "Part 5", title: "Glittering Cave & Grant",
    areas: "Route 8 · Ambrette Town · Route 9 · Glittering Cave · Cyllage City · Cyllage Gym",
    badge: "Cliff Badge (#2)",
    steps: [
      { id: "p5-route8", ref: "5#Sina_and_Dexio", type: "story", loc: "Route 8", title: "Route 8 (upper): south over the stepping stones",
        text: "Sina and Dexio add the <b>Coastal Kalos</b> Pokédex. Hop across the stones in the mud pit to Ambrette Town." },
      { id: "p5-lab", ref: "5#Fossil_Lab", type: "story", loc: "Ambrette Town", title: "Fossil Lab: their assistant is in Glittering Cave",
        text: "Serena/Calem meets you on the stairs into town. The Scientists don't know much about Mega Stones, but their field assistant might." },
      { id: "p5-rhyhorn", ref: "5#Ride_with_Rhyhorn", type: "story", loc: "Route 9", title: "Ride Rhyhorn east across Route 9",
        text: "Press A to smash the big rocks, B to get off." },
      { id: "p5-cave", ref: "5#1F", type: "story", loc: "Glittering Cave", title: "Glittering Cave: go straight at every junction",
        text: "The green crystals light the way down to the basement." },
      { id: "p5-flare", ref: "5#B1F", type: "story", loc: "Glittering Cave", title: "Team Flare appears: tag battle two Grunts with Serena/Calem",
        text: "Several Grunts are digging for Fossils. Near the end, Serena/Calem joins you against a pair of them." },
      { id: "p5-fossil", ref: "5#B1F", type: "story", loc: "Glittering Cave", title: "Pick a Fossil from the lab assistant",
        text: "The <b>Jaw Fossil</b> becomes Tyrunt (Rock/Dragon), the <b>Sail Fossil</b> becomes Amaura (Rock/Ice). The Escape Rope next to him warps you back to the entrance." },
      { id: "p5-restore", ref: "5#Fossil_Lab_2", type: "tip", loc: "Ambrette Town", title: "Restore your Fossil (Lv20) at the Fossil Lab",
        text: "A worker also gives you the Aerodactylite." },
      { id: "p5-lower", ref: "5#Route_8_(lower)", type: "story", loc: "Route 8", title: "Take Route 8's lower beach path north to Cyllage City", text: "" },
      { id: "p5-trade", ref: "5#Time_for_a_Trade", type: "tip", loc: "Cyllage City", title: "Trade a Luvdisc for Steelix",
        text: "In the Pokémon Center. Luvdisc is common in these waters, and Steelix is strong against the Gym." },
      { id: "p5-strength", ref: "5#Collect_an_HM", type: "story", loc: "Cyllage City", title: "Grant gives you HM04 Strength",
        text: "On the cliff road up to the Gym, at the first bend. You can use it once you have his badge." },
      { id: "p5-gym", ref: "5#Cyllage_Gym", type: "boss", loc: "Cyllage City", title: "Cyllage Gym: Grant",
        text: "Climb the rock walls to the Leader at the top.",
        boss: { who: "Gym Leader Grant", team: [["Amaura", 25, "Rock/Ice"], ["Tyrunt", 25, "Rock/Dragon"]],
          use: "<b>Fighting, Ground, Steel</b> (Amaura takes 4× from Fighting and Steel). Avoid Fire, Flying and Bug. Amaura uses Thunder Wave.", reward: "Cliff Badge + TM39 Rock Tomb" } },
    ],
  },

  /* ============================ PART 6 ============================ */
  {
    id: "p6", refs: [6], part: "Part 6", title: "Korrina & the Mega Ring",
    areas: "Route 10 · Geosenge Town · Route 11 · Reflection Cave · Shalour City · Tower of Mastery",
    badge: "Rumble Badge (#3)",
    steps: [
      { id: "p6-route10", ref: "6#Team_Flare", type: "story", loc: "Route 10", title: "North through the standing stones of Route 10",
        text: "Team Flare Grunts are studying the stones and want a rematch." },
      { id: "p6-geosenge", ref: "6#Team_Flare,_Again!", type: "story", loc: "Geosenge Town", title: "A Grunt disappears by a pile of rocks",
        text: "He vanishes in front of an odd rock pile in the northwest corner of town. Remember the spot." },
      { id: "p6-korrina", ref: "6#Battle_Korrina", type: "boss", loc: "Geosenge Town", title: "Korrina challenges you",
        boss: { who: "Gym Leader Korrina", team: [["Lucario", 25, "Fighting/Steel"], ["Lucario", 25, "Fighting/Steel"]],
          use: "<b>Fire, Fighting, Ground</b> (all 2×).", reward: "" } },
      { id: "p6-route11", ref: "6#Receive_a_Holo_Clip", type: "story", loc: "Route 11", title: "Route 11 to Reflection Cave",
        text: "Sycamore calls: visit the Mega Evolution guru in Shalour City." },
      { id: "p6-cave", ref: "6#1F", type: "story", loc: "Reflection Cave", title: "Through Reflection Cave",
        text: "<ol><li>1F: past the junction, go south to Battle Girl Hedvig, then east past Ace Trainer Monique and down the stairs.</li><li>B1F: a Pokémon Breeder heals you, and Tierno gives you TM70 Flash. Go southwest and down to B2F.</li><li>B2F: go west to what looks like a dead end and check the reflection on the north wall: it hides a tunnel. Take its south exit, jump the ledge east and go back up.</li><li>B1F: west from Ace Trainer Emil, then up the northwest stairs.</li><li>1F: push the Strength boulder into place and leave by the north exit.</li></ol>" },
      { id: "p6-stone", ref: "6#Hit_the_Beach!", type: "story", loc: "Shalour City", title: "Tierno gives you an Intriguing Stone on the beach",
        text: "Then go to the Tower of Mastery at the north end of town." },
      { id: "p6-rival", ref: "6#Tower_of_Mastery", type: "boss", loc: "Shalour City", title: "Tower of Mastery: battle Serena/Calem for the Mega Ring",
        text: "The guru (Korrina's grandfather) has only one Mega Ring. To really earn it you must also beat Korrina at her Gym.",
        boss: { who: RIVAL, rival: true, team: [["Meowstic", 28, "Psychic"], ["Absol", 28, "Dark"], ["$rmid", 30]],
          use: "Bug hits both Meowstic and Absol; Fighting and Fairy hit Absol.", reward: "" } },
      { id: "p6-gym", ref: "6#Shalour_Gym", type: "boss", loc: "Shalour City", title: "Shalour Gym: Korrina",
        text: "Beat the four Roller Skaters; each one raises part of the rail to the Leader.",
        boss: { who: "Gym Leader Korrina", team: [["Mienfoo", 29, "Fighting"], ["Machoke", 28, "Fighting"], ["Hawlucha", 32, "Fighting/Flying"]],
          use: "<b>Flying, Psychic, Fairy</b>. Avoid Normal, Rock, Steel, Ice and Dark. Hawlucha is fast; Electric and Ice also hit it.", reward: "Rumble Badge + TM98 Power-Up Punch" } },
      { id: "p6-mega", ref: "6#Tower_of_Mastery_2", type: "boss", loc: "Shalour City", title: "Top of the Tower: Mega Ring, then Lucario vs. Lucario",
        text: "On 5F Korrina gives you the <b>Mega Ring</b>, and one of her Lucario joins you for the battle.",
        boss: { who: "Successor Korrina", team: [["Lucario", 32, "Fighting/Steel", "Lucarionite"]],
          use: "Mega Evolve your Lucario right away and use Power-Up Punch.", reward: "Keep the Lucario" } },
      { id: "p6-surf", ref: "6#A_Gift", type: "story", loc: "Shalour City", title: "Serena/Calem gives you HM03 Surf",
        text: "At the east gate. Then take Route 12 east." },
    ],
  },

  /* ============================ PART 7 ============================ */
  {
    id: "p7", refs: [7], part: "Part 7", title: "Ramos & the Power Plant",
    areas: "Route 12 · Azure Bay · Coumarine City · Coumarine Gym · Route 13 · Kalos Power Plant",
    badge: "Plant Badge (#4)",
    steps: [
      { id: "p7-lapras", ref: "7#Adopt_a_Lapras", type: "tip", loc: "Route 12", title: "Free Lapras from the Breeder by the gate",
        text: "You need an empty party slot." },
      { id: "p7-route12", ref: "7#Route_12", type: "story", loc: "Route 12", title: "East along Route 12 to Coumarine City", text: "" },
      { id: "p7-den", ref: "7#Azure_Bay", type: "tip", loc: "Azure Bay", title: "Note the Sea Spirit's Den in Azure Bay",
        text: "The cave in the middle of the bay is empty for now. After the Hall of Fame, the legendary bird you can catch ends up here." },
      { id: "p7-fly", ref: "7#Lower", type: "story", loc: "Coumarine City", title: "Seaside Station: Sycamore gives you HM02 Fly",
        text: "Serena/Calem calls first and asks for a battle outside the Gym. Diantha is with the professor." },
      { id: "p7-rival", ref: "7#Upper", type: "boss", loc: "Coumarine City", title: "Battle Serena/Calem outside the Gym",
        text: "Take the monorail up to the Pokémon Center and the Gym.",
        boss: { who: RIVAL, rival: true, team: [["Meowstic", 31, "Psychic"], ["Absol", 31, "Dark"], ["$rmid", 33]],
          use: "Bug hits Meowstic and Absol; Fighting and Fairy hit Absol.", reward: "" } },
      { id: "p7-gym", ref: "7#Upper", type: "boss", loc: "Coumarine City", title: "Coumarine Gym: Ramos",
        text: "Climb and swing across the ropes on the big tree to the top (6F).",
        boss: { who: "Gym Leader Ramos", team: [["Jumpluff", 30, "Grass/Flying"], ["Weepinbell", 31, "Grass/Poison"], ["Gogoat", 34, "Grass"]],
          use: "<b>Fire, Flying</b> (also Poison, Bug, Ice; Jumpluff takes 4× from Ice). Avoid Water, Ground and Rock. Gogoat's Bulldoze hurts Fire types.", reward: "Plant Badge + TM86 Grass Knot" } },
      { id: "p7-gate", ref: "7#Upper", type: "story", loc: "Coumarine City", title: "South gate: the Power Plant has closed the way to Lumiose",
        text: "Sina and Dexio add the <b>Mountain Kalos</b> Pokédex." },
      { id: "p7-pass", ref: "7#Hidden_Items", type: "key", loc: "Route 13", title: "Dowse for the Power Plant Pass",
        text: "Use the Dowsing Machine in the southwest of Route 13: the pass is at a big boulder near a metal bridge. Beat the Grunt there and go in." },
      { id: "p7-plant", ref: "7#Kalos_Power_Plant", type: "boss", loc: "Kalos Power Plant", title: "Power Plant: beat Team Flare in the central room",
        text: "Fight past the Grunts around the outer walkway. In the middle, beat the Admin, then the Scientist Aliana. The masked Defenders of Kalos heal you and give you 2 Full Restores.",
        boss: { who: "Team Flare Aliana", team: [["Mightyena", 38, "Dark"]],
          use: "<b>Fighting, Bug, Fairy</b>.", reward: "Power restored" },
        after: "Then go north up Route 13 into Lumiose City." },
    ],
  },

  /* ============================ PART 8 ============================ */
  {
    id: "p8", refs: [8], part: "Part 8", title: "Clemont & Lysandre Café",
    areas: "Lumiose City · Prism Tower (Lumiose Gym)",
    badge: "Voltage Badge (#5)",
    steps: [
      { id: "p8-tower", ref: "8#North_Boulevard", type: "story", loc: "Lumiose City", title: "Shauna takes you to Prism Tower",
        text: "In Centrico Plaza you meet the Gym Leader <b>Clemont</b> and his sister <b>Bonnie</b> as the tower lights up." },
      { id: "p8-gym", ref: "8#Centrico_Plaza", type: "boss", loc: "Lumiose Gym", title: "Lumiose Gym: Clemont",
        text: "Bonnie's quiz: answer by battling the Trainer with that number. The right order is <b>#3 (Pikachu), #1 (Fletchling), #3 (Panpour), #2 (Vivillon)</b>. Wrong answers add extra battles.",
        boss: { who: "Gym Leader Clemont", team: [["Emolga", 35, "Electric/Flying"], ["Magneton", 35, "Electric/Steel"], ["Heliolisk", 37, "Electric/Normal"]],
          use: "<b>Ground</b> for Magneton and Heliolisk (Fighting too). Emolga is immune to Ground: use Rock or Ice. Magneton has Sturdy.", reward: "Voltage Badge + TM24 Thunderbolt" } },
      { id: "p8-cafe", ref: "8#Lysandre_Café", type: "story", loc: "Lysandre Café", title: "Lysandre Café: Sycamore and Lysandre",
        text: "Northwest of the Gym. Lysandre says he's related to a king of 3,000 years ago and gives you a King's Rock. Trevor then calls: meet on Route 14 (north)." },
    ],
  },

  /* ============================ PART 9 ============================ */
  {
    id: "p9", refs: [9], part: "Part 9", title: "Valerie & the Poké Ball Factory",
    areas: "Route 14 · Laverre City · Laverre Gym · Poké Ball Factory · Route 15",
    badge: "Fairy Badge (#6)",
    steps: [
      { id: "p9-rival", ref: "9#Rival_Battle", type: "boss", loc: "Route 14", title: "Route 14: battle Serena/Calem",
        text: "Just outside the Lumiose gate.",
        boss: { who: RIVAL, rival: true, team: [["Meowstic", 35, "Psychic"], ["Absol", 35, "Dark"], ["$race", 37]],
          use: "Bug hits Meowstic and Absol; Fairy and Fighting hit Absol.", reward: "" } },
      { id: "p9-route14", ref: "9#Scary_House", type: "story", loc: "Route 14", title: "North through the swamp to Laverre City",
        text: "Shauna drags you into the Scary House at the north end. Then continue to Laverre City." },
      { id: "p9-gym", ref: "9#Laverre_Gym", type: "boss", loc: "Laverre City", title: "Laverre Gym: Valerie",
        text: "A dollhouse of warp panels. Take the warp panel on the <b>right</b> side of each room.",
        boss: { who: "Gym Leader Valerie", team: [["Mawile", 38, "Steel/Fairy"], ["Mr. Mime", 39, "Psychic/Fairy"], ["Sylveon", 42, "Fairy"]],
          use: "<b>Poison, Steel</b>. Mawile resists both: use Fire or Ground on it. Avoid Dark, Dragon and Fighting. Sylveon's Cute Charm can infatuate.", reward: "Fairy Badge + TM99 Dazzling Gleam" } },
      { id: "p9-factory", ref: "9#Poké_Ball_Factory", type: "story", loc: "Poké Ball Factory", title: "Sneak into the Poké Ball Factory",
        text: "Shauna and Trevor ask you to tour it. Shauna lures the guard away. Inside: ride the first belt west then north, the second east then south, and climb the stairs. A worker in the northwest office heals you; reverse the belts at the control panel in the southwest corner, then ride east and climb to the president's office in the northeast." },
      { id: "p9-flare", ref: "9#Poké_Ball_Factory", type: "boss", loc: "Poké Ball Factory", title: "President's office: Team Flare Admin, then Celosia & Bryony",
        text: "Beat the Admin first. Then Celosia and Bryony battle you two-on-one, until Serena/Calem joins you.",
        boss: { who: "Bryony & Celosia (with Serena/Calem)", team: [["Liepard", 41, "Dark"], ["Manectric", 41, "Electric"]],
          use: "Fighting for Liepard, Ground for Manectric.", reward: "" } },
      { id: "p9-master", ref: "9#Poké_Ball_Factory", type: "key", loc: "Poké Ball Factory", title: "The president gives you the Master Ball",
        text: "He offers a Master Ball or a Big Nugget, then gives you both.",
        callout: "Save the <b>Master Ball</b> for a post-game legendary. Bulbapedia suggests Mewtwo." },
      { id: "p9-route15", ref: "9#Route_15", type: "story", loc: "Route 15", title: "Route 15 southeast to Dendemille Town",
        text: "Skip the Lost Hotel and Route 16 (side areas)." },
    ],
  },

  /* ============================ PART 10 ============================ */
  {
    id: "p10", refs: [10], part: "Part 10", title: "Frost Cavern & Olympia",
    areas: "Dendemille Town · Frost Cavern · Route 17 · Anistar City · Anistar Gym",
    badge: "Psychic Badge (#7)",
    steps: [
      { id: "p10-dendemille", ref: "10#Sycamore_Appears", type: "story", loc: "Dendemille Town", title: "Sycamore tells you about {Xerneas|Yveltal}",
        text: "When it loses its strength, the legendary sleeps in a secret place. Then go north to Frost Cavern: the Mamoswine you need for Route 17 won't move until you check what's wrong inside." },
      { id: "p10-cavern", ref: "10#Interior", type: "story", loc: "Frost Cavern", title: "Climb Frost Cavern to 3F",
        text: "<ol><li>1F: northeast across the ice, then east up the stairs.</li><li>2F: slide east and pass Hiker Delmon, then work southeast over the ice and take the southern stairs.</li><li>1F: an Ace Trainer heals you. Go north past Hiker Alain and up.</li><li>2F: straight up to 3F.</li><li>3F: get to Black Belt Kenji, then head north. (Sliding on southeast and down to 2F only leads to TM79 Frost Breath.)</li></ol>" },
      { id: "p10-mable", ref: "10#Interior", type: "boss", loc: "Frost Cavern", title: "Free the Abomasnow: Team Flare's Mable",
        text: "Beat two Grunts with Trevor's help, then Mable. Abomasnow gives you the Abomasite.",
        boss: { who: "Team Flare Mable", team: [["Houndoom", 48, "Dark/Fire"]],
          use: "<b>Water, Ground, Rock, Fighting</b>.", reward: "Abomasite" } },
      { id: "p10-route17", ref: "10#Hitch_a_Ride", type: "story", loc: "Route 17", title: "Ride Mamoswine through the snow to Anistar City",
        text: "Serena/Calem calls: they'll battle you in front of the Anistar Gym." },
      { id: "p10-rival", ref: "10#Rival_battle", type: "boss", loc: "Anistar City", title: "Battle Serena/Calem at the Gym",
        text: "Sina gives you 10 Repeat Balls when you arrive.",
        boss: { who: RIVAL, rival: true, team: [["Meowstic", 44, "Psychic"], ["Absol", 44, "Dark"], ["$reevee", 44], ["$race", 46]],
          use: "Bug hits Meowstic and Absol; Fighting and Fairy hit Absol.", reward: "" } },
      { id: "p10-gym", ref: "10#Anistar_Gym", type: "boss", loc: "Anistar City", title: "Anistar Gym: Olympia",
        text: "Stand in the middle to reveal the maze. Follow the yellow warp panels from the blue to the green to the pink paths, down to the Leader.",
        boss: { who: "Gym Leader Olympia", team: [["Sigilyph", 44, "Psychic/Flying"], ["Slowking", 45, "Water/Psychic"], ["Meowstic", 48, "Psychic"]],
          use: "<b>Bug, Ghost, Dark</b>; Electric for Sigilyph and Slowking. Avoid Fighting and Poison. Sigilyph sets up Reflect and Light Screen.", reward: "Psychic Badge + TM04 Calm Mind" } },
      { id: "p10-reveal", ref: "10#Holo_Clip_2", type: "story", loc: "Anistar City", title: "Lysandre reveals he leads Team Flare",
        text: "He plans to use an \"ultimate weapon\". Serena/Calem suggests looking for him where you first met him: <b>Lysandre Café</b> in Lumiose City." },
    ],
  },

  /* ============================ PART 11 ============================ */
  {
    id: "p11", refs: [11], part: "Part 11", title: "Team Flare & {Xerneas|Yveltal}",
    areas: "Lysandre Café · Lysandre Labs · Geosenge Town · Team Flare Secret HQ",
    intro: "Stock up on supplies before going into Lysandre Café: the labs and the Secret HQ are full of Team Flare.",
    steps: [
      { id: "p11-cafe", ref: "11#Lysandre_Café", type: "story", loc: "Lysandre Café", title: "Open the secret door in Lysandre Café",
        text: "Beat the two Grunts to learn the password, then examine the china cabinet on the far wall (\"open sesame\")." },
      { id: "p11-lysandre", ref: "11#Lysandre_Labs", type: "boss", loc: "Lysandre Labs", title: "Lysandre Labs B1F: Lysandre",
        boss: { who: "Team Flare Boss Lysandre", team: [["Mienfoo", 45, "Fighting"], ["Murkrow", 45, "Dark/Flying"], ["Pyroar", 47, "Fire/Normal"], ["Gyarados", 49, "Water/Flying"]],
          use: "Electric for Murkrow and Gyarados (4×), Water or Rock for Pyroar, Flying/Psychic/Fairy for Mienfoo.", reward: "" } },
      { id: "p11-aliana", ref: "11#Lysandre_Labs", type: "boss", loc: "Lysandre Labs", title: "Scientist 1: Aliana (northwest corner)",
        text: "Spin panels slide you until you hit a wall; warp panels teleport you. The first warp (west) leads to Aliana.",
        boss: { who: "Team Flare Aliana", team: [["Mightyena", 46, "Dark"], ["Druddigon", 48, "Dragon"]],
          use: "Fairy hits both. Fighting/Bug for Mightyena, Ice/Dragon for Druddigon.", reward: "" } },
      { id: "p11-rest", ref: "11#Lysandre_Labs", type: "heal", loc: "Lysandre Labs", title: "West room: rest in a bed",
        text: "The break room on B1F has beds that heal your team (and a Grunt who hands you TM12 Taunt)." },
      { id: "p11-celosia", ref: "11#Lysandre_Labs", type: "boss", loc: "Lysandre Labs", title: "Scientists 2 and 3: Celosia, then Bryony (northeast room)",
        text: "They explain the plan: the stolen power and the Geosenge stones will fuel the ultimate weapon.",
        boss: { who: "Team Flare Celosia", team: [["Manectric", 46, "Electric"], ["Drapion", 48, "Poison/Dark"]],
          use: "<b>Ground</b> hits both (4× on Drapion).", reward: "" } },
      { id: "p11-bryony", ref: "11#Lysandre_Labs", type: "boss", loc: "Lysandre Labs", title: "Bryony",
        boss: { who: "Team Flare Bryony", team: [["Liepard", 46, "Dark"], ["Bisharp", 48, "Dark/Steel"]],
          use: "<b>Fighting</b> (4× on Bisharp).", reward: "" } },
      { id: "p11-mable", ref: "11#Lysandre_Labs", type: "boss", loc: "Lysandre Labs", title: "Scientist 4: Mable (eastern room) has the Elevator Key",
        text: "From the three south spin panels take the easternmost, warp, go south to the Grunt in the southeast corner, warp, then northeast.",
        boss: { who: "Team Flare Mable", team: [["Houndoom", 46, "Dark/Fire"], ["Weavile", 48, "Dark/Ice"]],
          use: "<b>Fighting</b> (4× on Weavile); Water/Ground/Rock for Houndoom.", reward: "Elevator Key" } },
      { id: "p11-az", ref: "11#Lysandre_Labs", type: "story", loc: "Lysandre Labs", title: "B2F: Lysandre and his prisoner AZ",
        text: "Take the elevator to B2F. AZ tells you about the weapon. Lysandre heads to B3F." },
      { id: "p11-xerosic", ref: "11#Lysandre_Labs", type: "boss", loc: "Lysandre Labs", title: "B3F: Xerosic",
        boss: { who: "Team Flare Xerosic", team: [["Crobat", 46, "Poison/Flying"], ["Malamar", 48, "Dark/Psychic"]],
          use: "Electric/Ice/Psychic/Rock for Crobat, <b>Bug</b> (4×) for Malamar.", reward: "" },
        after: "Either button you press, the weapon wakes up in Geosenge Town. <b>Fly there</b>." },
      { id: "p11-enter", ref: "11#Enter_the_HQ", type: "story", loc: "Geosenge Town", title: "Enter the Secret HQ (the rock pile in the northwest)",
        text: "Beat the Grunt outside. Serena/Calem comes with you and fights on your side inside." },
      { id: "p11-lysandre2", ref: "11#Team_Flare_Secret_HQ", type: "boss", loc: "Team Flare Secret HQ", title: "1F: Lysandre stalls you",
        boss: { who: "Team Flare Boss Lysandre", team: [["Mienshao", 47, "Fighting"], ["Honchkrow", 47, "Dark/Flying"], ["Pyroar", 49, "Fire/Normal"], ["Gyarados", 51, "Water/Flying"]],
          use: "Electric for Honchkrow and Gyarados (4×), Water or Rock for Pyroar, Flying/Psychic/Fairy for Mienshao.", reward: "" } },
      { id: "p11-hall", ref: "11#Team_Flare_Secret_HQ", type: "story", loc: "Team Flare Secret HQ", title: "Down the hallway with Serena/Calem",
        text: "Take the northwest door. You and Serena/Calem fight pairs of Grunts and Admins. Shauna catches up and unlocks the basement door." },
      { id: "p11-basement", ref: "11#Team_Flare_Secret_HQ", type: "story", loc: "Team Flare Secret HQ", title: "Basement: beat the last Admins to free the legendary",
        text: "Shauna and Serena/Calem lure some away; beat the rest one by one." },
      { id: "p11-legend", ref: "11#Team_Flare_Secret_HQ", type: "legend", legend: "{xerneas|yveltal}", loc: "Team Flare Secret HQ", title: "{Xerneas|Yveltal} (Lv50)",
        text: "It must be caught before the story continues.",
        tactic: "{Poison and Steel hit hard; follow up with Bug, Dark or Fighting to chip it down. Watch for Geomancy, which sharply raises its Sp. Atk, Sp. Def and Speed.|Electric, Ice, Rock and Fairy hit hard; follow up with Ghost, Grass or Dark to chip it down. Oblivion Wing heals it.} Save before the battle." },
      { id: "p11-lysandre3", ref: "11#Team_Flare_Secret_HQ", type: "boss", loc: "Team Flare Secret HQ", title: "Final battle with Lysandre (Mega Gyarados)",
        boss: { who: "Team Flare Boss Lysandre", team: [["Mienshao", 49, "Fighting"], ["Honchkrow", 49, "Dark/Flying"], ["Pyroar", 51, "Fire/Normal"], ["Gyarados", 53, "Water/Flying", "Gyaradosite"]],
          use: "Mega Gyarados becomes <b>Water/Dark</b>: Electric, Grass, Fighting, Bug and Fairy all hit it. Electric for Honchkrow.", reward: "" } },
      { id: "p11-after", ref: "11#Aftermath", type: "story", loc: "Geosenge Town", title: "Aftermath: AZ's story; Sycamore calls you to Couriway Town",
        text: "The weapon fires and sinks back underground. AZ reveals he is the king who built it. Leaving Anistar, Sycamore asks you to meet him in Couriway Town (Route 18)." },
    ],
  },

  /* ============================ PART 12 ============================ */
  {
    id: "p12", refs: [12], part: "Part 12", title: "Couriway & Route 19",
    areas: "Route 18 · Couriway Town · Route 19",
    steps: [
      { id: "p12-route18", ref: "12#Terminus_Cave", type: "story", loc: "Route 18", title: "Route 18 southeast to Couriway Town",
        text: "Terminus Cave is on this route. An Ace Trainer blocks its deepest chamber until after the Hall of Fame: that's where Zygarde is." },
      { id: "p12-sycamore", ref: "12#Meet_up_with_Sycamore", type: "boss", loc: "Couriway Town", title: "Battle Professor Sycamore",
        boss: { who: "Pokémon Professor Sycamore", team: [["Venusaur", 50, "Grass/Poison"], ["Charizard", 50, "Fire/Flying"], ["Blastoise", 50, "Water"]],
          use: "Psychic/Fire/Ice/Flying for Venusaur, Rock (4×) or Electric/Water for Charizard, Electric or Grass for Blastoise.", reward: "" } },
      { id: "p12-shauna", ref: "12#Challenge_Accepted", type: "boss", loc: "Route 19", title: "Route 19 bridge: Shauna",
        boss: { who: "Pokémon Trainer Shauna", rival: true, team: [["Delcatty", 49, "Normal"], ["Goodra", 49, "Dragon"], ["$sace", 51]],
          use: "Fighting for Delcatty, Fairy/Ice/Dragon for Goodra.", reward: "" } },
      { id: "p12-tierno", ref: "12#Challenge_Accepted", type: "boss", loc: "Route 19", title: "Then Tierno",
        boss: { who: "Pokémon Trainer Tierno", team: [["Talonflame", 48, "Fire/Flying"], ["Roserade", 49, "Grass/Poison"], ["Crawdaunt", 52, "Water/Dark"]],
          use: "Rock (4×) or Electric for Talonflame; Fire/Ice/Flying/Psychic for Roserade; Electric, Grass, Fighting, Bug or Fairy for Crawdaunt.", reward: "" } },
      { id: "p12-trevor", ref: "12#Challenge_Accepted", type: "boss", loc: "Route 19", title: "Then Trevor (he heals you first)",
        boss: { who: "Pokémon Trainer Trevor", team: [["Raichu", 49, "Electric"], ["Aerodactyl", 49, "Rock/Flying"], ["Florges", 51, "Fairy"]],
          use: "Ground for Raichu; Water/Ice/Rock/Electric/Steel for Aerodactyl; Poison or Steel for Florges.", reward: "Waterfall (from Shauna)" },
        after: "Shauna gives you <b>Waterfall</b>. Continue southwest to Snowbelle City." },
    ],
  },

  /* ============================ PART 13 ============================ */
  {
    id: "p13", refs: [13], part: "Part 13", title: "The Winding Woods & Wulfric",
    areas: "Snowbelle City · Route 20 · Pokémon Village · Snowbelle Gym",
    badge: "Iceberg Badge (#8)",
    steps: [
      { id: "p13-snowbelle", ref: "13#Snowbelle_City", type: "story", loc: "Snowbelle City", title: "The Gym Leader is out: go find him in the Winding Woods",
        text: "Head south from Snowbelle City onto Route 20." },
      { id: "p13-woods", ref: "13#Route_20", type: "story", loc: "Route 20", title: "Find the way through the Winding Woods",
        text: "Some paths loop back. The way through: <ol><li>Entrance: south past the mossy boulder.</li><li>Area 1: west.</li><li>Area 2: north from the Twins.</li><li>Area 3: the southwest passage near Fairy Tale Girl Wynne.</li><li>Area 5 (J-shaped): east to the round clearing; you're moved to Area 6.</li><li>Area 6 (T-shaped): south.</li><li>Area 7: west (Cut the tree), then back east, which returns you to Area 5.</li><li>Area 5: southwest to the exit.</li></ol>" },
      { id: "p13-village", ref: "13#Meet_Wulfric", type: "story", loc: "Pokémon Village", title: "Pokémon Village: meet Wulfric",
        text: "He heads back to his Gym. Upriver is the <b>Unknown Dungeon</b>; a man won't let you in until you're Champion (Mewtwo is inside)." },
      { id: "p13-gym", ref: "13#Snowbelle_Gym", type: "boss", loc: "Snowbelle City", title: "Snowbelle Gym: Wulfric",
        text: "Each button rotates a part of the Gym. Pink ×2 to the blue platform; blue ×3; pink ×3 more to the center bridge; beat the two Ace Trainers there; yellow ×1, green ×3 to the Leader.",
        boss: { who: "Gym Leader Wulfric", team: [["Abomasnow", 56, "Grass/Ice"], ["Cryogonal", 55, "Ice"], ["Avalugg", 59, "Ice"]],
          use: "<b>Fire, Fighting, Rock, Steel</b> (Fire is 4× on Abomasnow). Avoid Grass, Flying, Ground and Dragon. Abomasnow starts a hailstorm. Hit Avalugg with special moves before it Curses up.", reward: "Iceberg Badge + TM13 Ice Beam" } },
    ],
  },

  /* ============================ PART 14 ============================ */
  {
    id: "p14", refs: [14], part: "Part 14", title: "Victory Road",
    areas: "Route 21 · Victory Road",
    steps: [
      { id: "p14-prep", ref: "13#Snowbelle_Gym", type: "prep", loc: "Snowbelle City", title: "Stock up on healing items in Snowbelle",
        text: "Full Restores, Revives and status heals for Victory Road and the League." },
      { id: "p14-route21", ref: "14#Route_21", type: "story", loc: "Route 21", title: "Route 21 northwest to Victory Road", text: "" },
      { id: "p14-gate", ref: "14#Gate", type: "story", loc: "Victory Road", title: "Gate: show your badges and beat Ace Trainer Robbie", text: "" },
      { id: "p14-road", ref: "14#Cave_1", type: "story", loc: "Victory Road", title: "Through the caves and groves",
        text: "Cave 1 → Grove 2 (cross the bridge) → Cave 2 (stepping stones and a Strength boulder) → Grove 3. A Pokémon Ranger in Grove 3 heals you." },
      { id: "p14-rival", ref: "14#Grove_3", type: "boss", loc: "Victory Road", title: "Grove 3: Serena/Calem's last battle",
        boss: { who: RIVAL, rival: true, team: [["Meowstic", 57, "Psychic"], ["$reevee", 57], ["Altaria", 58, "Dragon/Flying"], ["Absol", 59, "Dark"], ["$race", 61]],
          use: "Bug for Meowstic and Absol, Ice (4×) or Fairy for Altaria.", reward: "2 Max Revives" } },
      { id: "p14-end", ref: "14#Cave_3", type: "story", loc: "Victory Road", title: "Cave 3, Grove 4 and Cave 4 to the Pokémon League",
        text: "From the rival spot, go east into Cave 3 and out its east exit. In Grove 4, cross the bridge to the pier and Surf into the last cave, then climb the final stairway." },
    ],
  },

  /* ============================ PART 15 ============================ */
  {
    id: "p15", refs: [15], part: "Part 15", title: "The Elite Four & Diantha",
    areas: "Pokémon League · Lumiose City",
    intro: "You can fight the Elite Four in any order, so start with the easiest for your team. Each has 2 Full Restores; Diantha has 3. There's no turning back once you start.",
    steps: [
      { id: "p15-malva", ref: "15#Blazing_Chamber", type: "boss", loc: "Pokémon League", title: "Malva (Fire), northeast door",
        boss: { who: "Elite Four Malva", team: [["Pyroar", 63, "Fire/Normal"], ["Torkoal", 63, "Fire"], ["Chandelure", 63, "Ghost/Fire"], ["Talonflame", 65, "Fire/Flying"]],
          use: "<b>Water, Rock</b> hit all four; Ground hits three. Chandelure and Talonflame have Flame Body, so prefer special moves.", reward: "" } },
      { id: "p15-siebold", ref: "15#Flood_Chamber", type: "boss", loc: "Pokémon League", title: "Siebold (Water), southeast door",
        boss: { who: "Elite Four Siebold", team: [["Clawitzer", 63, "Water"], ["Gyarados", 63, "Water/Flying"], ["Starmie", 63, "Water/Psychic"], ["Barbaracle", 65, "Rock/Water"]],
          use: "<b>Electric</b> hits all four (4× on Gyarados); Grass hits most. Gyarados uses Dragon Dance and Earthquake.", reward: "" } },
      { id: "p15-wikstrom", ref: "15#Ironworks_Chamber", type: "boss", loc: "Pokémon League", title: "Wikstrom (Steel), northwest door",
        boss: { who: "Elite Four Wikstrom", team: [["Klefki", 63, "Steel/Fairy"], ["Probopass", 63, "Rock/Steel"], ["Scizor", 63, "Bug/Steel"], ["Aegislash", 65, "Steel/Ghost"]],
          use: "<b>Fire</b> for Klefki, Scizor (4×) and Aegislash; <b>Fighting or Ground</b> (4×) for Probopass, which has Sturdy.", reward: "" } },
      { id: "p15-drasna", ref: "15#Dragonmark_Chamber", type: "boss", loc: "Pokémon League", title: "Drasna (Dragon), southwest door",
        boss: { who: "Elite Four Drasna", team: [["Dragalge", 63, "Poison/Dragon"], ["Druddigon", 63, "Dragon"], ["Altaria", 63, "Dragon/Flying"], ["Noivern", 65, "Flying/Dragon"]],
          use: "<b>Ice</b> hits all four (4× on Altaria and Noivern). Fairy hits all but Dragalge.", reward: "" } },
      { id: "p15-diantha", ref: "15#Radiant_Chamber", type: "boss", loc: "Pokémon League", title: "Champion Diantha",
        boss: { who: "Champion Diantha", team: [["Hawlucha", 64, "Fighting/Flying"], ["Tyrantrum", 65, "Rock/Dragon"], ["Aurorus", 65, "Rock/Ice"], ["Gourgeist", 65, "Ghost/Grass"], ["Goodra", 66, "Dragon"], ["Gardevoir", 68, "Psychic/Fairy", "Gardevoirite"]],
          use: "Ice, Steel and Fairy cover most of her team. Mega Gardevoir is her ace: <b>Steel</b> Pokémon resist its Moonblast and Psychic.", reward: "Hall of Fame" } },
      { id: "p15-az", ref: "15#Lumiose_City", type: "boss", loc: "Lumiose City", title: "The parade: AZ asks for a battle",
        text: "Sycamore gives you the Honor of Kalos.",
        boss: { who: "Pokémon Trainer AZ", team: [["Torkoal", 60, "Fire"], ["Golurk", 60, "Ground/Ghost"], ["Sigilyph", 60, "Psychic/Flying"]],
          use: "Water or Ground for Torkoal, Water/Ice/Ghost/Dark for Golurk, Electric/Ice/Rock/Ghost/Dark for Sigilyph.", reward: "The credits roll" } },
    ],
  },

  /* ============================ POST-GAME ============================ */
  {
    id: "pg1", refs: [16, 17], part: "Post-game ①", title: "The roaming legendary bird",
    areas: "Vaniville Town · Lumiose Station · all of Kalos · Sea Spirit's Den",
    postgame: true,
    intro: "Only one of the Kanto birds appears in your game, picked by your starter: Chespin → Articuno, Fennekin → Zapdos, Froakie → Moltres.",
    steps: [
      { id: "pg-home", ref: "16#Homecoming", type: "story", loc: "Vaniville Town", title: "Mom: Sycamore is waiting at Lumiose Station", text: "" },
      { id: "pg-station", ref: "16#Lumiose_Station", type: "story", loc: "Lumiose City", title: "Lumiose Station: National Pokédex and the TMV Pass",
        text: "Sina and Dexio upgrade your Pokédex, and Sycamore gives you the TMV Pass." },
      { id: "pg-roam", ref: "17#Sea_Spirit's_Den", type: "key", loc: "Sea Spirit's Den", title: "Meet ${bird} and chase it 11 times",
        text: "The <b>first wild Pokémon you meet after Lumiose Station is ${bird}</b>. It flees at once and starts roaming Kalos; your Pokédex can now track where it is. After you've met it <b>eleven times</b>, it settles in the Sea Spirit's Den in Azure Bay." },
      { id: "pg-bird", ref: "17#Sea_Spirit's_Den", type: "legend", legend: "$bird", loc: "Sea Spirit's Den", title: "${bird} (Lv70) in the Sea Spirit's Den",
        text: "Surf to the cave in the middle of Azure Bay.",
        tactic: "Bring Ultra, Dusk, Quick or Timer Balls. Rock hits all three birds hard. If you run, it starts roaming again." },
    ],
  },
  {
    id: "pg2", refs: [17], part: "Post-game ②", title: "Mewtwo",
    areas: "Route 20 · Pokémon Village · Unknown Dungeon",
    postgame: true,
    steps: [
      { id: "pg-village", ref: "17#Unknown_Dungeon", type: "story", loc: "Pokémon Village", title: "Back through the Winding Woods to Pokémon Village",
        text: "Fly to Snowbelle City and walk Route 20 again. In the village, Surf upriver: the man guarding the cave is gone." },
      { id: "pg-mewtwo", ref: "17#Unknown_Dungeon", type: "legend", legend: "mewtwo", loc: "Unknown Dungeon", title: "Mewtwo (Lv70)",
        text: "A single small chamber. Mewtwo stands in the middle with its back to you.",
        tactic: "Bug, Ghost or Dark to weaken it, then Fighting or Psychic to chip it down. Spore or Thunder Wave keeps it from Recovering. Or use the Master Ball from the Poké Ball Factory." },
    ],
  },
  {
    id: "pg3", refs: [17], part: "Post-game ③", title: "Zygarde",
    areas: "Route 18 · Terminus Cave",
    postgame: true,
    steps: [
      { id: "pg-terminus", ref: "17#Terminus_Cave", type: "story", loc: "Terminus Cave", title: "Terminus Cave down to Zygarde's chamber",
        text: "<ol><li>1F: past the mine cart, down the northeast stairs.</li><li>B1F: south, down the slope, southwest over two ledges, across the bridges past Hiker Aaron, then north past Worker Dimitri and down the stairs.</li><li>B2F: work east past the Rangers to the last junction and climb the stairs to the east.</li><li>B1F (east): north, around the hill, and up the northwest stairs to the final chamber.</li></ol>" },
      { id: "pg-zygarde", ref: "17#Terminus_Cave", type: "legend", legend: "zygarde", loc: "Terminus Cave", title: "Zygarde (Lv70)",
        text: "It watches you from a hill where the four tunnels meet.",
        tactic: "Ice (4×), Dragon and Fairy to weaken it, then Fire, Poison or Rock to chip it down." },
    ],
  },
];

/* ---------------------------------------------------------------------------
   Game module registration — everything the shared renderer needs.
--------------------------------------------------------------------------- */
window.GAME = {
  id: "xy",
  gen: 6,                                   // Fairy type and Gen 6 typings in the Types panel
  skin: "kalos",                            // sleek Kalos look (css/style.css → body[data-skin="kalos"])
  title: "X & Y Legendary Route",
  tagline: "Main story, every gym and boss, then every catchable legendary",
  // First entry = text before "|" in {a|b} placeholders, second = after.
  versions: [
    { id: "x", label: "X", mode: "dark",  accent: "#2f7cf6", accent2: "#1c4fc4", ink: "#ffffff" },
    { id: "y", label: "Y", mode: "light", accent: "#e0283e", accent2: "#a8152a", ink: "#ffffff" },
  ],
  defaultVersion: "y",                      // the user plays Y
  sprites: "assets/sprites/gen6",           // {dex}.gif animated, {dex}.png still
  regionMaps: { x: { drive: "1kYnRwRArUx93Z0GLkO-bay4F10C9hoJm" }, y: { drive: "1kYnRwRArUx93Z0GLkO-bay4F10C9hoJm" } }, // MewMaps Kalos map
  regionName: "Kalos",
  pins: PINS,
  maps: MAPS,
  starter: {
    label: "Starter",
    options: [["chespin", "Chespin"], ["fennekin", "Fennekin"], ["froakie", "Froakie"]],
    // Rival Serena/Calem has the starter strong against yours ("rmid"/"race"), plus an Eeveelution
    // ("reevee"); Shauna has the one weak to yours ("sbase"/"sace"). "bird" is the roaming legendary.
    slots: {
      chespin:  { rmid: ["Braixen", "Fire"],     race: ["Delphox", "Fire/Psychic"],     reevee: ["Jolteon", "Electric"], sbase: ["Froakie", "Water"],  sace: ["Greninja", "Water/Dark"],      bird: ["Articuno", "Ice/Flying"] },
      fennekin: { rmid: ["Frogadier", "Water"],  race: ["Greninja", "Water/Dark"],      reevee: ["Flareon", "Fire"],     sbase: ["Chespin", "Grass"],  sace: ["Chesnaught", "Grass/Fighting"], bird: ["Zapdos", "Electric/Flying"] },
      froakie:  { rmid: ["Quilladin", "Grass"],  race: ["Chesnaught", "Grass/Fighting"], reevee: ["Vaporeon", "Water"],   sbase: ["Fennekin", "Fire"],  sace: ["Delphox", "Fire/Psychic"],     bird: ["Moltres", "Fire/Flying"] },
    },
  },
  legends: LEGENDS,
  notInGame: NOT_IN_GAME,
  catchKit: [
    "<b>Master Ball</b> (Poké Ball Factory): Bulbapedia suggests Mewtwo",
    "<b>TM54 False Swipe</b> (Sycamore's lab): never knocks out",
    "<b>Dusk Balls</b> in caves, <b>Timer Balls</b> for long fights, a <b>Quick Ball</b> on turn 1",
    "<b>Repeat Balls</b>: Sina gives you 10 in Anistar City",
    "Sleep or Paralysis user (Spore, Thunder Wave)",
    "<b>Save before every legendary</b>",
  ],
  postgameBanner: "🏆 Post-game: the legendary hunt. Everything below happens after you enter the Hall of Fame.",
  chapters: CHAPTERS,
  // Step/part links: ref "11#Lysandre_Labs" → <base>11#Lysandre_Labs
  walkthrough: {
    label: "Bulbapedia",
    base: "https://bulbapedia.bulbagarden.net/wiki/Walkthrough:Pok%C3%A9mon_X_and_Y/Part_",
    partLabel: (n) => `Part ${n}`,
    sections: SECTIONS,
  },
  sources: [
    ["Bulbapedia X and Y walkthrough", "https://bulbapedia.bulbagarden.net/wiki/Walkthrough:Pok%C3%A9mon_X_and_Y"],
    ["MewMaps", "https://www.mewmaps.org/x-y"],
  ],
};
})();
