"""Build assets/pokedex.js (every Pokémon's English name + types, with older-generation types)
from PokéAPI's public CSV data. Re-run when adding a game past the current MAX_DEX:

    python tools/build-pokedex.py
"""
import csv, io, json, os, urllib.request

MAX_DEX = 809  # through Gen 7 (Ultra Sun / Ultra Moon)
SRC = "https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/"
OUT = os.path.join(os.path.dirname(__file__), "..", "assets", "pokedex.js")


def table(name):
    with urllib.request.urlopen(SRC + name + ".csv", timeout=60) as r:
        return list(csv.DictReader(io.StringIO(r.read().decode("utf-8"))))


types = {t["id"]: t["identifier"].capitalize() for t in table("types")}
names = {n["pokemon_species_id"]: n["name"] for n in table("pokemon_species_names") if n["local_language_id"] == "9"}
# Default form of each species only (regional forms etc. can be added later if a game needs them).
default = {p["id"]: p["species_id"] for p in table("pokemon") if p["is_default"] == "1" and int(p["species_id"]) <= MAX_DEX}

cur, past = {}, {}
for t in table("pokemon_types"):
    if t["pokemon_id"] in default:
        cur.setdefault(int(default[t["pokemon_id"]]), []).append((int(t["slot"]), types[t["type_id"]]))
for t in table("pokemon_types_past"):  # types a Pokémon had up to and including generation_id
    if t["pokemon_id"] in default:
        past.setdefault((int(default[t["pokemon_id"]]), int(t["generation_id"])), []).append((int(t["slot"]), types[t["type_id"]]))

join = lambda slots: "/".join(n for _, n in sorted(slots))
mons = [[d, names[str(d)], join(cur[d])] for d in sorted(cur)]
older = {}
for (d, gen), slots in sorted(past.items()):
    older.setdefault(str(d), []).append([gen, join(slots)])

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("/* Generated by tools/build-pokedex.py from PokéAPI data. Don't edit by hand.\n"
            "   POKEDEX: [dex, name, types] for every Pokémon through #%d (default forms).\n"
            "   POKEDEX_PAST: dex → [[lastGen, types], …] — the types it had up to and including lastGen. */\n" % MAX_DEX)
    f.write("const POKEDEX = [\n" + ",\n".join(json.dumps(m, ensure_ascii=False) for m in mons) + "\n];\n")
    f.write("const POKEDEX_PAST = " + json.dumps(older, ensure_ascii=False) + ";\n")
print("wrote %d Pokemon, %d with older types -> %s" % (len(mons), len(older), os.path.normpath(OUT)))
